Enum = {
	ActionBarOrientation = {
		Horizontal = 0,
		Vertical = 1,
	},
	ActionBarVisibleSetting = {
		Always = 0,
		InCombat = 1,
		OutOfCombat = 2,
		Hidden = 3,
	},
	AddSoulbindConduitReason = {
		None = 0,
		Cheat = 1,
		SpellEffect = 2,
		Upgrade = 3,
	},
	AnimaDiversionNodeState = {
		Unavailable = 0,
		Available = 1,
		SelectedTemporary = 2,
		SelectedPermanent = 3,
		Cooldown = 4,
	},
	AuctionHouseCommoditySortOrder = {
		UnitPrice = 0,
		Quantity = 1,
	},
	AuctionHouseError = {
		NotEnoughMoney = 0,
		HigherBid = 1,
		BidIncrement = 2,
		BidOwn = 3,
		ItemNotFound = 4,
		RestrictedAccountTrial = 5,
		HasRestriction = 6,
		IsBusy = 7,
		Unavailable = 8,
		ItemHasQuote = 9,
		DatabaseError = 10,
		MinBid = 11,
		NotEnoughItems = 12,
		RepairItem = 13,
		UsedCharges = 14,
		QuestItem = 15,
		BoundItem = 16,
		ConjuredItem = 17,
		LimitedDurationItem = 18,
		IsBag = 19,
		EquippedBag = 20,
		WrappedItem = 21,
		LootItem = 22,
		DoubleBid = 23,
		FavoritesMaxed = 24,
		ItemNotAvailable = 25,
	},
	AuctionHouseExtraColumn = {
		None = 0,
		Ilvl = 1,
		Slots = 2,
		Level = 3,
		Skill = 4,
	},
	AuctionHouseFilter = {
		None = 0,
		UncollectedOnly = 1,
		UsableOnly = 2,
		UpgradesOnly = 3,
		ExactMatch = 4,
		PoorQuality = 5,
		CommonQuality = 6,
		UncommonQuality = 7,
		RareQuality = 8,
		EpicQuality = 9,
		LegendaryQuality = 10,
		ArtifactQuality = 11,
		LegendaryCraftedItemOnly = 12,
	},
	AuctionHouseFilterCategory = {
		Uncategorized = 0,
		Equipment = 1,
		Rarity = 2,
	},
	AuctionHouseItemSortOrder = {
		Bid = 0,
		Buyout = 1,
	},
	AuctionHouseNotification = {
		BidPlaced = 0,
		AuctionRemoved = 1,
		AuctionWon = 2,
		AuctionOutbid = 3,
		AuctionSold = 4,
		AuctionExpired = 5,
	},
	AuctionHouseSortOrder = {
		Price = 0,
		Name = 1,
		Level = 2,
		Bid = 3,
		Buyout = 4,
		TimeRemaining = 5,
	},
	AuctionHouseTimeLeftBand = {
		Short = 0,
		Medium = 1,
		Long = 2,
		VeryLong = 3,
	},
	AuctionStatus = {
		Active = 0,
		Sold = 1,
	},
	AuraFrameIconDirection = {
		Down = 0,
		Left = 0,
		Right = 1,
		Up = 1,
	},
	AuraFrameIconWrap = {
		Down = 0,
		Left = 0,
		Right = 1,
		Up = 1,
	},
	AuraFrameOrientation = {
		Horizontal = 0,
		Vertical = 1,
	},
	AzeriteEssenceSlot = {
		MainSlot = 0,
		PassiveOneSlot = 1,
		PassiveTwoSlot = 2,
		PassiveThreeSlot = 3,
	},
	AzeritePowerLevel = {
		Base = 0,
		Upgraded = 1,
		Downgraded = 2,
	},
	BagIndex = {
		Bankbag = -4,
		Reagentbank = -3,
		Keyring = -2,
		Bank = -1,
		Backpack = 0,
		Bag_1 = 1,
		Bag_2 = 2,
		Bag_3 = 3,
		Bag_4 = 4,
		ReagentBag = 5,
		BankBag_1 = 6,
		BankBag_2 = 7,
		BankBag_3 = 8,
		BankBag_4 = 9,
		BankBag_5 = 10,
		BankBag_6 = 11,
		BankBag_7 = 12,
	},
	BagSlotFlags = {
		DisableAutoSort = 0x1,
		PriorityEquipment = 0x2,
		PriorityConsumables = 0x4,
		PriorityTradeGoods = 0x8,
		PriorityJunk = 0x10,
		PriorityQuestItems = 0x20,
		BagSlotPriorityFlagsAll = 0x3E,
		BagSlotValidFlagsAll = 0x3F,
	},
	BagsDirection = {
		Left = 0,
		Up = 0,
		Down = 1,
		Right = 1,
	},
	BagsOrientation = {
		Horizontal = 0,
		Vertical = 1,
	},
	BattlePetAbilityFlag = {
		DisplayAsHostileDebuff = 0x1,
		HideStrongWeakHints = 0x2,
		Passive = 0x4,
		ServerOnlyAura = 0x8,
		ShowCast = 0x10,
		StartOnCooldown = 0x20,
	},
	BattlePetAbilitySlot = {
		A = 0,
		B = 1,
		C = 2,
	},
	BattlePetAbilityTargets = {
		EnemyFrontPet = 0,
		FriendlyFrontPet = 1,
		Weather = 2,
		EnemyPad = 3,
		FriendlyPad = 4,
		EnemyBackPet_1 = 5,
		EnemyBackPet_2 = 6,
		FriendlyBackPet_1 = 7,
		FriendlyBackPet_2 = 8,
		Caster = 9,
		Owner = 10,
		Specific = 11,
		ProcTarget = 12,
	},
	BattlePetAbilityTurnFlag = {
		CanProcFromProc = 0x1,
		TriggerBySelf = 0x2,
		TriggerByFriend = 0x4,
		TriggerByEnemy = 0x8,
		TriggerByWeather = 0x10,
		TriggerByAuraCaster = 0x20,
	},
	BattlePetAbilityTurnType = {
		Normal = 0,
		TriggeredEffect = 1,
	},
	BattlePetAbilityType = {
		Ability = 0,
		Aura = 1,
	},
	BattlePetAction = {
		None = 0,
		Ability = 1,
		SwitchPet = 2,
		Trap = 3,
		Skip = 4,
	},
	BattlePetBreedQuality = {
		Poor = 0,
		Common = 1,
		Uncommon = 2,
		Rare = 3,
		Epic = 4,
		Legendary = 5,
	},
	BattlePetEffectFlags = {
		EnableAbilityPicker = 1,
		LuaNeedsAllPets = 2,
	},
	BattlePetEffectParamType = {
		Int = 0,
		Ability = 1,
	},
	BattlePetEvent = {
		OnAuraApplied = 0,
		OnDamageTaken = 1,
		OnDamageDealt = 2,
		OnHealTaken = 3,
		OnHealDealt = 4,
		OnAuraRemoved = 5,
		OnRoundStart = 6,
		OnRoundEnd = 7,
		OnTurn = 8,
		OnAbility = 9,
		OnSwapIn = 10,
		OnSwapOut = 11,
		PostAuraTicks = 12,
	},
	BattlePetNpcEmote = {
		BattleUnused = 0,
		BattleStart = 1,
		BattleWin = 2,
		BattleLose = 3,
		PetSwap = 4,
		PetKill = 5,
		PetDie = 6,
		PetAbility = 7,
	},
	BattlePetNpcTeamFlag = {
		MatchPlayerHighPetLevel = 1,
		NoPlayerXP = 2,
	},
	BattlePetOwner = {
		Weather = 0,
		Ally = 1,
		Enemy = 2,
	},
	BattlePetSources = {
		Drop = 0,
		Quest = 1,
		Vendor = 2,
		Profession = 3,
		WildPet = 4,
		Achievement = 5,
		WorldEvent = 6,
		Promotion = 7,
		Tcg = 8,
		PetStore = 9,
		Discovery = 10,
	},
	BattlePetSpeciesFlags = {
		NoRename = 0x1,
		WellKnown = 0x2,
		NotAcccountwide = 0x4,
		Capturable = 0x8,
		NotTradable = 0x10,
		HideFromJournal = 0x20,
		LegacyAccountUnique = 0x40,
		CantBattle = 0x80,
		HordeOnly = 0x100,
		AllianceOnly = 0x200,
		Boss = 0x400,
		RandomDisplay = 0x800,
		NoLicenseRequired = 0x1000,
		AddsAllowedWithBoss = 0x2000,
		HideUntilLearned = 0x4000,
		MatchPlayerHighPetLevel = 0x8000,
		NoWildPetAddsAllowed = 0x10000,
	},
	BattlePetStateFlag = {
		None = 0x0,
		SwapOutLock = 0x1,
		TurnLock = 0x2,
		SpeedBonus = 0x4,
		Client = 0x8,
		MaxHealthBonus = 0x10,
		Stamina = 0x20,
		QualityDoesNotEffect = 0x40,
		DynamicScaling = 0x80,
		Power = 0x100,
		SpeedMult = 0x200,
		SwapInLock = 0x400,
		ServerOnly = 0x800,
	},
	BattlePetTypes = {
		Humanoid = 0,
		Dragonkin = 1,
		Flying = 2,
		Undead = 3,
		Critter = 4,
		Magic = 5,
		Elemental = 6,
		Beast = 7,
		Aquatic = 8,
		Mechanical = 9,
	},
	BattlePetVisualFlag = {
		Test1 = 1,
		Test2 = 2,
		Test3 = 4,
	},
	BattlePetVisualRange = {
		Melee = 0,
		Ranged = 1,
		InPlace = 2,
		PointBlank = 3,
		BehindMelee = 4,
		BehindRanged = 5,
	},
	BattlepetDbFlags = {
		None = 0x0,
		Favorite = 0x1,
		Converted = 0x2,
		Revoked = 0x4,
		LockedForConvert = 0x8,
		LockMask = 0xC,
		Ability0Selection = 0x10,
		Ability1Selection = 0x20,
		Ability2Selection = 0x40,
		FanfareNeeded = 0x80,
		DisplayOverridden = 0x100,
		AcquiredViaLicense = 0x200,
		TradingPost = 0x400,
	},
	BattlepetDeletedReason = {
		Unknown = 0,
		PlayerReleased = 1,
		PlayerCaged = 2,
		Gm = 3,
		CageError = 4,
		DelJournal = 5,
	},
	BattlepetSlotLockCheat = {
		Cheat_2_Locked = -3,
		Cheat_1_Locked = -2,
		Cheat_0_Locked = -1,
		CheatOff = 0,
		UnlockAll = 1,
	},
	BindingSet = {
		Default = 0,
		Account = 1,
		Character = 2,
		Current = 3,
	},
	BrawlType = {
		None = 0,
		Battleground = 1,
		Arena = 2,
		LFG = 3,
		SoloShuffle = 4,
	},
	CachedRewardType = {
		None = 0,
		Item = 1,
		Currency = 2,
		Quest = 3,
	},
	CalendarCommandType = {
		Create = 0,
		Invite = 1,
		Rsvp = 2,
		RemoveInvite = 3,
		RemoveEvent = 4,
		Status = 5,
		ModeratorStatus = 6,
		GetCalendar = 7,
		GetEvent = 8,
		UpdateEvent = 9,
		Complain = 10,
		Notes = 11,
	},
	CalendarErrorType = {
		Success = 0,
		CommunityEventsExceeded = 1,
		EventsExceeded = 2,
		SelfInvitesExceeded = 3,
		OtherInvitesExceeded = 4,
		NoPermission = 5,
		EventInvalid = 6,
		NotInvited = 7,
		UnknownError = 8,
		NotInGuild = 9,
		NotInCommunity = 10,
		TargetAlreadyInvited = 11,
		NameNotFound = 12,
		WrongFaction = 13,
		Ignored = 14,
		InvitesExceeded = 15,
		InvalidMaxSize = 16,
		InvalidDate = 17,
		InvalidTime = 18,
		NoInvites = 19,
		NeedsTitle = 20,
		EventPassed = 21,
		EventLocked = 22,
		DeleteCreatorFailed = 23,
		DataAlreadySet = 24,
		CalendarDisabled = 25,
		RestrictedAccount = 26,
		ArenaEventsExceeded = 27,
		RestrictedLevel = 28,
		Squelched = 29,
		NoInvite = 30,
		ComplaintDisabled = 31,
		ComplaintSelf = 32,
		ComplaintSameGuild = 33,
		ComplaintGm = 34,
		ComplaintLimit = 35,
		ComplaintNotFound = 36,
		EventWrongServer = 37,
		NoCommunityInvites = 38,
		InvalidSignup = 39,
		NoModerator = 40,
		ModeratorRestricted = 41,
		InvalidNotes = 42,
		InvalidTitle = 43,
		InvalidDescription = 44,
		InvalidClub = 45,
		CreatorNotFound = 46,
		EventThrottled = 47,
		InviteThrottled = 48,
		Internal = 49,
		ComplaintAdded = 50,
	},
	CalendarEventBits = {
		Player = 0x1,
		GuildDeprecated = 0x2,
		System = 0x4,
		Holiday = 0x8,
		Locked = 0x10,
		AutoApprove = 0x20,
		CommunityAnnouncement = 0x40,
		RaidLockout = 0x80,
		ArenaDeprecated = 0x100,
		RaidResetDeprecated = 0x200,
		CommunitySignup = 0x400,
		GuildSignup = 0x800,
		CommunityWide = 0xC40,
		PlayerCreated = 0xD43,
		CantComplain = 0xECC,
	},
	CalendarEventRepeatOptions = {
		Never = 0,
		Weekly = 1,
		Biweekly = 2,
		Monthly = 3,
	},
	CalendarEventType = {
		Raid = 0,
		Dungeon = 1,
		PvP = 2,
		Meeting = 3,
		Other = 4,
		HeroicDeprecated = 5,
	},
	CalendarFilterFlags = {
		WeeklyHoliday = 0x1,
		Darkmoon = 0x2,
		Battleground = 0x4,
		RaidLockout = 0x8,
		RaidReset = 0x10,
	},
	CalendarGetEventType = {
		Get = 0,
		Add = 1,
		Copy = 2,
	},
	CalendarHolidayFilterType = {
		Weekly = 0,
		Darkmoon = 1,
		Battleground = 2,
	},
	CalendarInviteBits = {
		PendingInvite = 0x1,
		Moderator = 0x2,
		Creator = 0x4,
		Signup = 0x8,
	},
	CalendarInviteSortType = {
		Name = 0,
		Level = 1,
		Class = 2,
		Status = 3,
		Party = 4,
		Notes = 5,
	},
	CalendarInviteType = {
		Normal = 0,
		Signup = 1,
	},
	CalendarModeratorStatus = {
		None = 0,
		Moderator = 1,
		Creator = 2,
	},
	CalendarStatus = {
		Invited = 0,
		Available = 1,
		Declined = 2,
		Confirmed = 3,
		Out = 4,
		Standby = 5,
		Signedup = 6,
		NotSignedup = 7,
		Tentative = 8,
	},
	CalendarTexturesType = {
		Dungeons = 0,
		Raid = 1,
	},
	CalendarType = {
		Player = 0,
		Community = 1,
		RaidLockout = 2,
		RaidResetDeprecated = 3,
		Holiday = 4,
		HolidayWeekly = 5,
		HolidayDarkmoon = 6,
		HolidayBattleground = 7,
	},
	CalendarWebActionType = {
		Accept = 0,
		Decline = 1,
		Remove = 2,
		ReportSpam = 3,
		Signup = 4,
		Tentative = 5,
		TentativeSignup = 6,
	},
	CallingStates = {
		QuestOffer = 0,
		QuestActive = 1,
		QuestCompleted = 2,
	},
	CampaignState = {
		Invalid = 0,
		Complete = 1,
		InProgress = 2,
		Stalled = 3,
	},
	CaptureBarWidgetFillDirectionType = {
		RightToLeft = 0,
		LeftToRight = 1,
	},
	CaptureBarWidgetGlowAnimType = {
		None = 0,
		Pulse = 1,
	},
	CharCustomizationType = {
		Skin = 0,
		Face = 1,
		Hair = 2,
		HairColor = 3,
		FacialHair = 4,
		CustomOptionTattoo = 5,
		CustomOptionHorn = 6,
		CustomOptionFacewear = 7,
		CustomOptionTattooColor = 8,
		Outfit = 9,
		Facepaint = 10,
		FacepaintColor = 11,
	},
	CharacterServiceInfoFlag = {
		RestrictToRecommendedSpecs = 1,
	},
	ChatChannelRuleset = {
		None = 0,
		Mentor = 1,
		Disabled = 2,
		ChromieTimeCataclysm = 3,
		ChromieTimeBuringCrusade = 4,
		ChromieTimeWrath = 5,
		ChromieTimeMists = 6,
		ChromieTimeWoD = 7,
		ChromieTimeLegion = 8,
	},
	ChatChannelType = {
		None = 0,
		Custom = 1,
		Private_Party = 2,
		Public_Party = 3,
		Communities = 4,
	},
	ChrCustomizationCategoryFlag = {
		UndressModel = 1,
	},
	ChrCustomizationOptionType = {
		SelectionPopout = 0,
		Checkbox = 1,
		Slider = 2,
	},
	ClickBindingInteraction = {
		Target = 1,
		OpenContextMenu = 2,
	},
	ClickBindingType = {
		None = 0,
		Spell = 1,
		Macro = 2,
		Interaction = 3,
	},
	ClientPlatformType = {
		Windows = 0,
		Macintosh = 1,
	},
	ClientSceneType = {
		DefaultSceneType = 0,
		MinigameSceneType = 1,
	},
	ClubActionType = {
		ErrorClubActionSubscribe = 0,
		ErrorClubActionCreate = 1,
		ErrorClubActionEdit = 2,
		ErrorClubActionDestroy = 3,
		ErrorClubActionLeave = 4,
		ErrorClubActionCreateTicket = 5,
		ErrorClubActionDestroyTicket = 6,
		ErrorClubActionRedeemTicket = 7,
		ErrorClubActionGetTicket = 8,
		ErrorClubActionGetTickets = 9,
		ErrorClubActionGetBans = 10,
		ErrorClubActionGetInvitations = 11,
		ErrorClubActionRevokeInvitation = 12,
		ErrorClubActionAcceptInvitation = 13,
		ErrorClubActionDeclineInvitation = 14,
		ErrorClubActionCreateStream = 15,
		ErrorClubActionEditStream = 16,
		ErrorClubActionDestroyStream = 17,
		ErrorClubActionInviteMember = 18,
		ErrorClubActionEditMember = 19,
		ErrorClubActionEditMemberNote = 20,
		ErrorClubActionKickMember = 21,
		ErrorClubActionAddBan = 22,
		ErrorClubActionRemoveBan = 23,
		ErrorClubActionCreateMessage = 24,
		ErrorClubActionEditMessage = 25,
		ErrorClubActionDestroyMessage = 26,
	},
	ClubErrorType = {
		ErrorCommunitiesNone = 0,
		ErrorCommunitiesUnknown = 1,
		ErrorCommunitiesNeutralFaction = 2,
		ErrorCommunitiesUnknownRealm = 3,
		ErrorCommunitiesBadTarget = 4,
		ErrorCommunitiesWrongFaction = 5,
		ErrorCommunitiesRestricted = 6,
		ErrorCommunitiesIgnored = 7,
		ErrorCommunitiesGuild = 8,
		ErrorCommunitiesWrongRegion = 9,
		ErrorCommunitiesUnknownTicket = 10,
		ErrorCommunitiesMissingShortName = 11,
		ErrorCommunitiesProfanity = 12,
		ErrorCommunitiesTrial = 13,
		ErrorCommunitiesVeteranTrial = 14,
		ErrorCommunitiesChatMute = 15,
		ErrorClubFull = 16,
		ErrorClubNoClub = 17,
		ErrorClubNotMember = 18,
		ErrorClubAlreadyMember = 19,
		ErrorClubNoSuchMember = 20,
		ErrorClubNoSuchInvitation = 21,
		ErrorClubInvitationAlreadyExists = 22,
		ErrorClubInvalidRoleID = 23,
		ErrorClubInsufficientPrivileges = 24,
		ErrorClubTooManyClubsJoined = 25,
		ErrorClubVoiceFull = 26,
		ErrorClubStreamNoStream = 27,
		ErrorClubStreamInvalidName = 28,
		ErrorClubStreamCountAtMin = 29,
		ErrorClubStreamCountAtMax = 30,
		ErrorClubMemberHasRequiredRole = 31,
		ErrorClubSentInvitationCountAtMax = 32,
		ErrorClubReceivedInvitationCountAtMax = 33,
		ErrorClubTargetIsBanned = 34,
		ErrorClubBanAlreadyExists = 35,
		ErrorClubBanCountAtMax = 36,
		ErrorClubTicketCountAtMax = 37,
		ErrorClubTicketNoSuchTicket = 38,
		ErrorClubTicketHasConsumedAllowedRedeemCount = 39,
		ErrorClubDoesntAllowCrossFaction = 40,
		ErrorClubEditHasCrossFactionMembers = 41,
	},
	ClubFieldType = {
		ClubName = 0,
		ClubShortName = 1,
		ClubDescription = 2,
		ClubBroadcast = 3,
		ClubStreamName = 4,
		ClubStreamSubject = 5,
		NumTypes = 6,
	},
	ClubFinderApplicationUpdateType = {
		None = 0,
		AcceptInvite = 1,
		DeclineInvite = 2,
		Cancel = 3,
	},
	ClubFinderClubPostingStatusFlags = {
		None = 0,
		NeedsCacheUpdate = 1,
		ForceDescriptionChange = 2,
		ForceNameChange = 3,
		UnderReview = 4,
		Banned = 5,
		FakePost = 6,
		PendingDelete = 7,
		PostDelisted = 8,
	},
	ClubFinderDisableReason = {
		Muted = 0,
		Silenced = 1,
		VeteranTrial = 2,
	},
	ClubFinderPostingReportType = {
		PostersName = 0,
		ClubName = 1,
		PostingDescription = 2,
		ApplicantsName = 3,
		JoinNote = 4,
	},
	ClubFinderRequestType = {
		None = 0,
		Guild = 1,
		Community = 2,
		All = 3,
	},
	ClubFinderSettingFlags = {
		None = 0,
		Dungeons = 1,
		Raids = 2,
		PvP = 3,
		RP = 4,
		Social = 5,
		Small = 6,
		Medium = 7,
		Large = 8,
		Tank = 9,
		Healer = 10,
		Damage = 11,
		EnableListing = 12,
		MaxLevelOnly = 13,
		AutoAccept = 14,
		FactionHorde = 15,
		FactionAlliance = 16,
		FactionNeutral = 17,
		SortRelevance = 18,
		SortMemberCount = 19,
		SortNewest = 20,
		LanguageReserved1 = 21,
		LanguageReserved2 = 22,
		LanguageReserved3 = 23,
		LanguageReserved4 = 24,
		LanguageReserved5 = 25,
	},
	ClubInvitationCandidateStatus = {
		Available = 0,
		InvitePending = 1,
		AlreadyMember = 2,
	},
	ClubMemberPresence = {
		Unknown = 0,
		Online = 1,
		OnlineMobile = 2,
		Offline = 3,
		Away = 4,
		Busy = 5,
	},
	ClubRemovedReason = {
		None = 0,
		Banned = 1,
		Removed = 2,
		ClubDestroyed = 3,
	},
	ClubRestrictionReason = {
		None = 0,
		Unavailable = 1,
	},
	ClubRoleIdentifier = {
		Owner = 1,
		Leader = 2,
		Moderator = 3,
		Member = 4,
	},
	ClubStreamNotificationFilter = {
		None = 0,
		Mention = 1,
		All = 2,
	},
	ClubStreamType = {
		General = 0,
		Guild = 1,
		Officer = 2,
		Other = 3,
	},
	ClubType = {
		BattleNet = 0,
		Character = 1,
		Guild = 2,
		Other = 3,
	},
	CommunicationMode = {
		PushToTalk = 0,
		OpenMic = 1,
	},
	ConquestProgressBarDisplayType = {
		FirstChest = 0,
		AdditionalChest = 1,
		Seasonal = 2,
	},
	ConsoleCategory = {
		Debug = 0,
		Graphics = 1,
		Console = 2,
		Combat = 3,
		Game = 4,
		Default = 5,
		Net = 6,
		Sound = 7,
		Gm = 8,
		Reveal = 9,
		None = 10,
	},
	ConsoleColorType = {
		DefaultColor = 0,
		InputColor = 1,
		EchoColor = 2,
		ErrorColor = 3,
		WarningColor = 4,
		GlobalColor = 5,
		AdminColor = 6,
		HighlightColor = 7,
		BackgroundColor = 8,
		ClickbufferColor = 9,
		PrivateColor = 10,
		DefaultGreen = 11,
	},
	ConsoleCommandType = {
		Cvar = 0,
		Command = 1,
		Macro = 2,
		Script = 3,
	},
	ContributionAppearanceFlags = {
		TooltipUseTimeRemaining = 0,
	},
	ContributionResult = {
		Success = 0,
		MustBeNearNpc = 1,
		IncorrectState = 2,
		InvalidID = 3,
		QuestDataMissing = 4,
		FailedConditionCheck = 5,
		UnableToCompleteTurnIn = 6,
		InternalError = 7,
	},
	ContributionState = {
		None = 0,
		Building = 1,
		Active = 2,
		UnderAttack = 3,
		Destroyed = 4,
	},
	CovenantAbilityType = {
		Class = 0,
		Signature = 1,
		Soulbind = 2,
	},
	CovenantSkill = {
		Kyrian = 2730,
		Venthyr = 2731,
		NightFae = 2732,
		Necrolord = 2733,
	},
	CovenantType = {
		None = 0,
		Kyrian = 1,
		Venthyr = 2,
		NightFae = 3,
		Necrolord = 4,
	},
	CraftingOrderCustomerCategoryType = {
		Primary = 0,
		Secondary = 1,
		Tertiary = 2,
	},
	CraftingOrderDuration = {
		Short = 0,
		Medium = 1,
		Long = 2,
	},
	CraftingOrderFlags = {
		IsRecraft = 0x1,
		HasNoneReagents = 0x2,
		HasSomeReagents = 0x4,
		HasAllReagents = 0x8,
		IsFulfillable = 0x10,
	},
	CraftingOrderItemType = {
		Reagent = 0,
		Recraft = 1,
		CraftedResult = 2,
	},
	CraftingOrderReagentSource = {
		Any = 0,
		Customer = 1,
		Crafter = 2,
		None = 3,
	},
	CraftingOrderReagentsType = {
		All = 0,
		Some = 1,
		None = 2,
	},
	CraftingOrderResult = {
		Ok = 0,
		Aborted = 1,
		AlreadyClaimed = 2,
		AlreadyCrafted = 3,
		CannotBeOrdered = 4,
		CannotCancel = 5,
		CannotClaim = 6,
		CannotClaimOwnOrder = 7,
		CannotCraft = 8,
		CannotCreate = 9,
		CannotFulfill = 10,
		CannotRecraft = 11,
		CannotReject = 12,
		CannotRelease = 13,
		CrafterIsIgnored = 14,
		DatabaseError = 15,
		Expired = 16,
		Locked = 17,
		InvalidDuration = 18,
		InvalidMinQuality = 19,
		InvalidNotes = 20,
		InvalidReagent = 21,
		InvalidRealm = 22,
		InvalidRecipe = 23,
		InvalidSort = 24,
		InvalidTarget = 25,
		InvalidType = 26,
		MaxOrdersReached = 27,
		MissingCraftingTable = 28,
		MissingItem = 29,
		MissingNpc = 30,
		MissingOrder = 31,
		MissingRecraftItem = 32,
		NotClaimed = 33,
		NotCrafted = 34,
		NotInGuild = 35,
		NotYetImplemented = 36,
		OutOfPublicOrderCapacity = 37,
		ServerIsNotAvailable = 38,
		ThrottleViolation = 39,
		TargetCannotCraft = 40,
		TargetLocked = 41,
		Timeout = 42,
		TooManyItems = 43,
		WrongVersion = 44,
	},
	CraftingOrderSortType = {
		ItemName = 0,
		AveTip = 1,
		MaxTip = 2,
		Quantity = 3,
		Reagents = 4,
		Tip = 5,
		TimeRemaining = 6,
		Status = 7,
	},
	CraftingOrderState = {
		None = 0,
		Creating = 1,
		Created = 2,
		Claiming = 3,
		Claimed = 4,
		Rejecting = 5,
		Rejected = 6,
		Releasing = 7,
		Crafting = 8,
		Recrafting = 9,
		Fulfilling = 10,
		Fulfilled = 11,
		Canceling = 12,
		Canceled = 13,
		Expiring = 14,
		Expired = 15,
	},
	CraftingOrderType = {
		Public = 0,
		Guild = 1,
		Personal = 2,
	},
	CraftingReagentItemFlag = {
		TooltipShowsAsStatModifications = 0,
	},
	CraftingReagentType = {
		Optional = 0,
		Basic = 1,
		Finishing = 2,
	},
	CurrencyDestroyReason = {
		Cheat = 0,
		Spell = 1,
		VersionUpdate = 2,
		QuestTurnin = 3,
		Vendor = 4,
		Trade = 5,
		Capped = 6,
		Garrison = 7,
		DroppedToCorpse = 8,
		BonusRoll = 9,
		FactionConversion = 10,
		FulfillCraftingOrder = 11,
		Last = 12,
	},
	CurrencyFlags = {
		CurrencyTradable = 0x1,
		CurrencyAppearsInLootWindow = 0x2,
		CurrencyComputedWeeklyMaximum = 0x4,
		Currency_100_Scaler = 0x8,
		CurrencyNoLowLevelDrop = 0x10,
		CurrencyIgnoreMaxQtyOnLoad = 0x20,
		CurrencyLogOnWorldChange = 0x40,
		CurrencyTrackQuantity = 0x80,
		CurrencyResetTrackedQuantity = 0x100,
		CurrencyUpdateVersionIgnoreMax = 0x200,
		CurrencySuppressChatMessageOnVersionChange = 0x400,
		CurrencySingleDropInLoot = 0x800,
		CurrencyHasWeeklyCatchup = 0x1000,
		CurrencyDoNotCompressChat = 0x2000,
		CurrencyDoNotLogAcquisitionToBi = 0x4000,
		CurrencyNoRaidDrop = 0x8000,
		CurrencyNotPersistent = 0x10000,
		CurrencyDeprecated = 0x20000,
		CurrencyDynamicMaximum = 0x40000,
		CurrencySuppressChatMessages = 0x80000,
		CurrencyDoNotToast = 0x100000,
		CurrencyDestroyExtraOnLoot = 0x200000,
		CurrencyDontShowTotalInTooltip = 0x400000,
		CurrencyDontCoalesceInLootWindow = 0x800000,
		CurrencyAccountWide = 0x1000000,
		CurrencyAllowOverflowMailer = 0x2000000,
		CurrencyHideAsReward = 0x4000000,
		CurrencyHasWarmodeBonus = 0x8000000,
		CurrencyIsAllianceOnly = 0x10000000,
		CurrencyIsHordeOnly = 0x20000000,
		CurrencyLimitWarmodeBonusOncePerTooltip = 0x40000000,
		DeprecatedCurrencyFlag = 0x80000000,
	},
	CurrencyFlagsB = {
		CurrencyBUseTotalEarnedForEarned = 0x1,
		CurrencyBShowQuestXPGainInTooltip = 0x2,
		CurrencyBNoNotificationMailOnOfflineProgress = 0x4,
		CurrencyBBattlenetVirtualCurrency = 0x8,
	},
	CurrencyGainFlags = {
		BonusAward = 1,
		DroppedFromDeath = 2,
		FromAccountServer = 4,
	},
	CurrencySource = {
		ConvertOldItem = 0,
		ConvertOldPvPCurrency = 1,
		ItemRefund = 2,
		QuestReward = 3,
		Cheat = 4,
		Vendor = 5,
		PvPKillCredit = 6,
		PvPMetaCredit = 7,
		PvPScriptedAward = 8,
		Loot = 9,
		UpdatingVersion = 10,
		LFGReward = 11,
		Trade = 12,
		Spell = 13,
		ItemDeletion = 14,
		RatedBattleground = 15,
		RandomBattleground = 16,
		Arena = 17,
		ExceededMaxQty = 18,
		PvPCompletionBonus = 19,
		Script = 20,
		GuildBankWithdrawal = 21,
		Pushloot = 22,
		GarrisonBuilding = 23,
		PvPDrop = 24,
		GarrisonFollowerActivation = 25,
		GarrisonBuildingRefund = 26,
		GarrisonMissionReward = 27,
		GarrisonResourceOverTime = 28,
		QuestRewardIgnoreCaps = 29,
		GarrisonTalent = 30,
		GarrisonWorldQuestBonus = 31,
		PvPHonorReward = 32,
		BonusRoll = 33,
		AzeriteRespec = 34,
		WorldQuestReward = 35,
		WorldQuestRewardIgnoreCaps = 36,
		FactionConversion = 37,
		DailyQuestReward = 38,
		DailyQuestWarModeReward = 39,
		WeeklyQuestReward = 40,
		WeeklyQuestWarModeReward = 41,
		AccountCopy = 42,
		WeeklyRewardChest = 43,
		GarrisonTalentTreeReset = 44,
		DailyReset = 45,
		AddConduitToCollection = 46,
		Barbershop = 47,
		ConvertItemsToCurrencyValue = 48,
		PvPTeamContribution = 49,
		Transmogrify = 50,
		AuctionDeposit = 51,
		PlayerTrait = 52,
		PhBuffer_53 = 53,
		PhBuffer_54 = 54,
		RenownRepGain = 55,
		CraftingOrder = 56,
		CatalystBalancing = 57,
		CatalystCraft = 58,
		ProfessionInitialAward = 59,
		PlayerTraitRefund = 60,
		Last = 61,
	},
	CurrencyTokenCategoryFlags = {
		FlagSortLast = 0x1,
		FlagPlayerItemAssignment = 0x2,
		Hidden = 0x4,
		Virtual = 0x8,
	},
	CursorStyle = {
		Mouse = 0,
		Crosshair = 1,
	},
	Cursormode = {
		NoCursor = 0,
		PointCursor = 1,
		CastCursor = 2,
		BuyCursor = 3,
		AttackCursor = 4,
		InteractCursor = 5,
		SpeakCursor = 6,
		InspectCursor = 7,
		PickupCursor = 8,
		TaxiCursor = 9,
		TrainerCursor = 10,
		MineCursor = 11,
		SkinCursor = 12,
		GatherCursor = 13,
		LockCursor = 14,
		MailCursor = 15,
		LootAllCursor = 16,
		RepairCursor = 17,
		RepairnpcCursor = 18,
		ItemCursor = 19,
		SkinHordeCursor = 20,
		SkinAllianceCursor = 21,
		InnkeeperCursor = 22,
		CampaignQuestCursor = 23,
		CampaignQuestTurninCursor = 24,
		QuestCursor = 25,
		QuestRepeatableCursor = 26,
		QuestTurninCursor = 27,
		VehicleCursor = 28,
		MapPinCursor = 29,
		UIMoveCursor = 30,
		UIResizeCursor = 31,
		PointErrorCursor = 32,
		CastErrorCursor = 33,
		BuyErrorCursor = 34,
		AttackErrorCursor = 35,
		InteractErrorCursor = 36,
		SpeakErrorCursor = 37,
		InspectErrorCursor = 38,
		PickupErrorCursor = 39,
		TaxiErrorCursor = 40,
		TrainerErrorCursor = 41,
		MineErrorCursor = 42,
		SkinErrorCursor = 43,
		GatherErrorCursor = 44,
		LockErrorCursor = 45,
		MailErrorCursor = 46,
		LootAllErrorCursor = 47,
		RepairErrorCursor = 48,
		RepairnpcErrorCursor = 49,
		ItemErrorCursor = 50,
		SkinHordeErrorCursor = 51,
		SkinAllianceErrorCursor = 52,
		InnkeeperErrorCursor = 53,
		CampaignQuestErrorCursor = 54,
		CampaignQuestTurninErrorCursor = 55,
		QuestErrorCursor = 56,
		QuestRepeatableErrorCursor = 57,
		QuestTurninErrorCursor = 58,
		VehicleErrorCursor = 59,
		MapPinErrorCursor = 60,
		CustomCursor = 61,
	},
	CustomBindingType = {
		VoicePushToTalk = 0,
	},
	CustomizationScope = {
		Player = 0,
		DragonCompanion = 1,
	},
	Damageclass = {
		MaskNone = 0x0,
		Physical = 0x0,
		AllPhysical = 0x1,
		Holy = 0x1,
		MaskPhysical = 0x1,
		Fire = 0x2,
		FirstResist = 0x2,
		MaskHoly = 0x2,
		MaskHolystrike = 0x3,
		Nature = 0x3,
		Frost = 0x4,
		MaskFire = 0x4,
		MaskFlamestrike = 0x5,
		Shadow = 0x5,
		Arcane = 0x6,
		LastResist = 0x6,
		MaskHolyfire = 0x6,
		NumClasses = 0x7,
		MaskNature = 0x8,
		MaskStormstrike = 0x9,
		MaskHolystorm = 0xA,
		MaskFirestorm = 0xC,
		MaskFrost = 0x10,
		MaskFroststrike = 0x11,
		MaskHolyfrost = 0x12,
		MaskFrostfire = 0x14,
		MaskFroststorm = 0x18,
		MaskElemental = 0x1C,
		MaskShadow = 0x20,
		MaskShadowstrike = 0x21,
		MaskTwilight = 0x22,
		MaskShadowflame = 0x24,
		MaskShadowstorm = 0x28,
		MaskShadowfrost = 0x30,
		MaskChromatic = 0x3E,
		MaskArcane = 0x40,
		MaskSpellstrike = 0x41,
		MaskDivine = 0x42,
		MaskSpellfire = 0x44,
		MaskSpellstorm = 0x48,
		MaskSpellfrost = 0x50,
		MaskSpellshadow = 0x60,
		MaskCosmic = 0x6A,
		MaskChaos = 0x7C,
		AllMagical = 0x7E,
		MaskMagical = 0x7E,
		All = 0x7F,
	},
	DamageclassType = {
		Physical = 0,
		Magical = 1,
	},
	EditModeAccountSetting = {
		ShowGrid = 0,
		GridSpacing = 1,
		SettingsExpanded = 2,
		ShowTargetAndFocus = 3,
		ShowStanceBar = 4,
		ShowPetActionBar = 5,
		ShowPossessActionBar = 6,
		ShowCastBar = 7,
		ShowEncounterBar = 8,
		ShowExtraAbilities = 9,
		ShowBuffFrame = 10,
		ShowDebuffFrame = 11,
		ShowPartyFrames = 12,
		ShowRaidFrames = 13,
		ShowTalkingHeadFrame = 14,
		ShowVehicleLeaveButton = 15,
		ShowBossFrames = 16,
		ShowArenaFrames = 17,
		ShowLootFrame = 18,
		ShowHudTooltip = 19,
		ShowReputationBar = 20,
		ShowDurabilityFrame = 21,
		EnableSnap = 22,
	},
	EditModeActionBarSetting = {
		Orientation = 0,
		NumRows = 1,
		NumIcons = 2,
		IconSize = 3,
		IconPadding = 4,
		VisibleSetting = 5,
		HideBarArt = 6,
		DeprecatedSnapToSide = 7,
		HideBarScrolling = 8,
		AlwaysShowButtons = 9,
	},
	EditModeActionBarSystemIndices = {
		MainBar = 1,
		Bar2 = 2,
		Bar3 = 3,
		RightBar1 = 4,
		RightBar2 = 5,
		ExtraBar1 = 6,
		ExtraBar2 = 7,
		ExtraBar3 = 8,
		StanceBar = 11,
		PetActionBar = 12,
		PossessActionBar = 13,
	},
	EditModeAuraFrameSetting = {
		Orientation = 0,
		IconWrap = 1,
		IconDirection = 2,
		IconLimitBuffFrame = 3,
		IconLimitDebuffFrame = 4,
		IconSize = 5,
		IconPadding = 6,
		DeprecatedShowFull = 7,
	},
	EditModeAuraFrameSystemIndices = {
		BuffFrame = 1,
		DebuffFrame = 2,
	},
	EditModeBagsSetting = {
		Orientation = 0,
		Direction = 1,
		Size = 2,
	},
	EditModeCastBarSetting = {
		BarSize = 0,
		LockToPlayerFrame = 1,
	},
	EditModeChatFrameSetting = {
		WidthHundreds = 0,
		WidthTensAndOnes = 1,
		HeightHundreds = 2,
		HeightTensAndOnes = 3,
	},
	EditModeDurabilityFrameSetting = {
		Size = 0,
	},
	EditModeLayoutType = {
		Preset = 0,
		Account = 1,
		Character = 2,
	},
	EditModeMicroMenuSetting = {
		Orientation = 0,
		Order = 1,
		Size = 2,
	},
	EditModeMinimapSetting = {
		HeaderUnderneath = 0,
		RotateMinimap = 1,
	},
	EditModeObjectiveTrackerSetting = {
		Height = 0,
	},
	EditModePresetLayouts = {
		Modern = 0,
		Classic = 1,
	},
	EditModeSettingDisplayType = {
		Dropdown = 0,
		Checkbox = 1,
		Slider = 2,
	},
	EditModeStatusTrackingBarSetting = {
		Height = 0,
		Width = 1,
		TextSize = 2,
	},
	EditModeStatusTrackingBarSystemIndices = {
		ExperienceBar = 1,
		ReputationBar = 2,
	},
	EditModeSystem = {
		ActionBar = 0,
		CastBar = 1,
		Minimap = 2,
		UnitFrame = 3,
		EncounterBar = 4,
		ExtraAbilities = 5,
		AuraFrame = 6,
		TalkingHeadFrame = 7,
		ChatFrame = 8,
		VehicleLeaveButton = 9,
		LootFrame = 10,
		HudTooltip = 11,
		ObjectiveTracker = 12,
		MicroMenu = 13,
		Bags = 14,
		StatusTrackingBar = 15,
		DurabilityFrame = 16,
	},
	EditModeUnitFrameSetting = {
		HidePortrait = 0,
		CastBarUnderneath = 1,
		BuffsOnTop = 2,
		UseLargerFrame = 3,
		UseRaidStylePartyFrames = 4,
		ShowPartyFrameBackground = 5,
		UseHorizontalGroups = 6,
		CastBarOnSide = 7,
		ShowCastTime = 8,
		ViewRaidSize = 9,
		FrameWidth = 10,
		FrameHeight = 11,
		DisplayBorder = 12,
		RaidGroupDisplayType = 13,
		SortPlayersBy = 14,
		RowSize = 15,
		FrameSize = 16,
	},
	EditModeUnitFrameSystemIndices = {
		Player = 1,
		Target = 2,
		Focus = 3,
		Party = 4,
		Raid = 5,
		Boss = 6,
		Arena = 7,
	},
	EnvironmentalDamageFlags = {
		OneTime = 1,
		DmgIsPct = 2,
	},
	Environmentaldamagetype = {
		Fatigue = 0,
		Drowning = 1,
		Falling = 2,
		Lava = 3,
		Slime = 4,
		Fire = 5,
	},
	EventToastDisplayType = {
		NormalSingleLine = 0,
		NormalBlockText = 1,
		NormalTitleAndSubTitle = 2,
		NormalTextWithIcon = 3,
		LargeTextWithIcon = 4,
		NormalTextWithIconAndRarity = 5,
		Scenario = 6,
		ChallengeMode = 7,
		ScenarioClickExpand = 8,
	},
	EventToastEventType = {
		LevelUp = 0,
		LevelUpSpell = 1,
		LevelUpDungeon = 2,
		LevelUpRaid = 3,
		LevelUpPvP = 4,
		PetBattleNewAbility = 5,
		PetBattleFinalRound = 6,
		PetBattleCapture = 7,
		BattlePetLevelChanged = 8,
		BattlePetLevelUpAbility = 9,
		QuestBossEmote = 10,
		MythicPlusWeeklyRecord = 11,
		QuestTurnedIn = 12,
		WorldStateChange = 13,
		Scenario = 14,
		LevelUpOther = 15,
		PlayerAuraAdded = 16,
		PlayerAuraRemoved = 17,
		SpellScript = 18,
		CriteriaUpdated = 19,
		PvPTierUpdate = 20,
		SpellLearned = 21,
		TreasureItem = 22,
	},
	ExpansionLandingPageType = {
		None = 0,
		Dragonflight = 1,
	},
	FlightPathFaction = {
		Neutral = 0,
		Horde = 1,
		Alliance = 2,
	},
	FlightPathState = {
		Current = 0,
		Reachable = 1,
		Unreachable = 2,
	},
	FollowerAbilityCastResult = {
		Success = 0,
		Failure = 1,
		NoPendingCast = 2,
		InvalidTarget = 3,
		InvalidFollowerSpell = 4,
		RerollNotAllowed = 5,
		SingleMissionDuration = 6,
		MustTargetFollower = 7,
		MustTargetTrait = 8,
		InvalidFollowerType = 9,
		MustBeUnique = 10,
		CannotTargetLimitedUseFollower = 11,
		MustTargetLimitedUseFollower = 12,
		AlreadyAtMaxDurability = 13,
		CannotTargetNonAutoMissionFollower = 14,
	},
	GamePadPowerLevel = {
		Critical = 0,
		Low = 1,
		Medium = 2,
		High = 3,
		Wired = 4,
		Unknown = 5,
	},
	GarrAutoBoardIndex = {
		None = -1,
		AllyLeftBack = 0,
		AllyRightBack = 1,
		AllyLeftFront = 2,
		AllyCenterFront = 3,
		AllyRightFront = 4,
		EnemyLeftFront = 5,
		EnemyCenterLeftFront = 6,
		EnemyCenterRightFront = 7,
		EnemyRightFront = 8,
		EnemyLeftBack = 9,
		EnemyCenterLeftBack = 10,
		EnemyCenterRightBack = 11,
		EnemyRightBack = 12,
	},
	GarrAutoCombatSpellTutorialFlag = {
		None = 0,
		Single = 1,
		Column = 2,
		Row = 3,
		All = 4,
	},
	GarrAutoCombatTutorial = {
		SelectMission = 0x1,
		PlaceCompanion = 0x2,
		HealCompanion = 0x4,
		LevelHeal = 0x8,
		BeneficialEffect = 0x10,
		AttackSingle = 0x20,
		AttackColumn = 0x40,
		AttackRow = 0x80,
		AttackAll = 0x100,
		TroopTutorial = 0x200,
		EnvironmentalEffect = 0x400,
	},
	GarrAutoCombatantRole = {
		None = 0,
		Melee = 1,
		RangedPhysical = 2,
		RangedMagic = 3,
		HealSupport = 4,
		Tank = 5,
	},
	GarrAutoEventFlags = {
		None = 0,
		AutoAttack = 1,
		Passive = 2,
		Environment = 4,
	},
	GarrAutoMissionEventType = {
		MeleeDamage = 0,
		RangeDamage = 1,
		SpellMeleeDamage = 2,
		SpellRangeDamage = 3,
		Heal = 4,
		PeriodicDamage = 5,
		PeriodicHeal = 6,
		ApplyAura = 7,
		RemoveAura = 8,
		Died = 9,
	},
	GarrAutoPreviewTargetType = {
		None = 0x0,
		Damage = 0x1,
		Heal = 0x2,
		Buff = 0x4,
		Debuff = 0x8,
	},
	GarrFollowerMissionCompleteState = {
		Alive = 0,
		KilledByMissionFailure = 1,
		SavedByPreventDeath = 2,
		OutOfDurability = 3,
	},
	GarrFollowerQuality = {
		None = 0,
		Common = 1,
		Uncommon = 2,
		Rare = 3,
		Epic = 4,
		Legendary = 5,
		Title = 6,
	},
	GarrTalentCostType = {
		Initial = 0,
		Respec = 1,
		MakePermanent = 2,
		TreeReset = 3,
	},
	GarrTalentFeatureSubtype = {
		Generic = 0,
		Bastion = 1,
		Revendreth = 2,
		Ardenweald = 3,
		Maldraxxus = 4,
	},
	GarrTalentFeatureType = {
		Generic = 0,
		AnimaDiversion = 1,
		TravelPortals = 2,
		Adventures = 3,
		ReservoirUpgrades = 4,
		SanctumUnique = 5,
		SoulBinds = 6,
		AnimaDiversionMap = 7,
		Cyphers = 8,
	},
	GarrTalentResearchCostSource = {
		Talent = 0,
		Tree = 1,
	},
	GarrTalentSocketType = {
		None = 0,
		Spell = 1,
		Conduit = 2,
	},
	GarrTalentTreeType = {
		Tiers = 0,
		Classic = 1,
	},
	GarrTalentType = {
		Standard = 0,
		Minor = 1,
		Major = 2,
		Socket = 3,
	},
	GarrTalentUI = {
		Generic = 0,
		CovenantSanctum = 1,
		SoulBinds = 2,
		AnimaDiversionMap = 3,
	},
	GarrisonFollowerType = {
		FollowerType_6_0 = 1,
		FollowerType_6_2 = 2,
		FollowerType_7_0 = 4,
		FollowerType_8_0 = 22,
		FollowerType_9_0 = 123,
	},
	GarrisonTalentAvailability = {
		Available = 0,
		Unavailable = 1,
		UnavailableAnotherIsResearching = 2,
		UnavailableNotEnoughResources = 3,
		UnavailableNotEnoughGold = 4,
		UnavailableTierUnavailable = 5,
		UnavailablePlayerCondition = 6,
		UnavailableAlreadyHave = 7,
		UnavailableRequiresPrerequisiteTalent = 8,
	},
	GarrisonType = {
		Type_6_0 = 2,
		Type_7_0 = 3,
		Type_8_0 = 9,
		Type_9_0 = 111,
	},
	GossipNpcOption = {
		None = 0,
		Vendor = 1,
		Taxinode = 2,
		Trainer = 3,
		SpiritHealer = 4,
		Binder = 5,
		Banker = 6,
		PetitionVendor = 7,
		TabardVendor = 8,
		Battlemaster = 9,
		Auctioneer = 10,
		TalentMaster = 11,
		Stablemaster = 12,
		PetSpecializationMaster = 13,
		GuildBanker = 14,
		Spellclick = 15,
		DisableXPGain = 16,
		EnableXPGain = 17,
		Mailbox = 18,
		WorldPvPQueue = 19,
		LFGDungeon = 20,
		ArtifactRespec = 21,
		CemeterySelect = 22,
		SpecializationMaster = 23,
		GlyphMaster = 24,
		QueueScenario = 25,
		GarrisonArchitect = 26,
		GarrisonMissionNpc = 27,
		ShipmentCrafter = 28,
		GarrisonTradeskillNpc = 29,
		GarrisonRecruitment = 30,
		AdventureMap = 31,
		GarrisonTalent = 32,
		ContributionCollector = 33,
		Transmogrify = 34,
		AzeriteRespec = 35,
		IslandsMissionNpc = 36,
		UIItemInteraction = 37,
		WorldMap = 38,
		Soulbind = 39,
		ChromieTimeNpc = 40,
		CovenantPreviewNpc = 41,
		RuneforgeLegendaryCrafting = 42,
		NewPlayerGuide = 43,
		RuneforgeLegendaryUpgrade = 44,
		CovenantRenownNpc = 45,
		BlackMarketAuctionHouse = 46,
		PerksProgramVendor = 47,
		ProfessionsCraftingOrder = 48,
		ProfessionsOpen = 49,
		ProfessionsCustomerOrder = 50,
		TraitSystem = 51,
		BarbersChoice = 52,
		MajorFactionRenown = 53,
	},
	GossipNpcOptionDisplayFlags = {
		ForceInteractionOnSingleChoice = 1,
	},
	GossipOptionRecFlags = {
		QuestLabelPrepend = 1,
	},
	GossipOptionRewardType = {
		Item = 0,
		Currency = 1,
	},
	GossipOptionStatus = {
		Available = 0,
		Unavailable = 1,
		Locked = 2,
		AlreadyComplete = 3,
	},
	GraphicsValidationResult = {
		Supported = 0,
		Illegal = 1,
		Unsupported = 2,
		Graphics = 3,
		DualCore = 4,
		QuadCore = 5,
		CpuMem_2 = 6,
		CpuMem_4 = 7,
		CpuMem_8 = 8,
		Needs_5_0 = 9,
		Needs_6_0 = 10,
		NeedsRt = 11,
		NeedsDx12 = 12,
		NeedsDx12Vrs2 = 13,
		NeedsAppleGpu = 14,
		NeedsAmdGpu = 15,
		NeedsIntelGpu = 16,
		NeedsNvidiaGpu = 17,
		NeedsQualcommGpu = 18,
		NeedsMacOs_10_13 = 19,
		NeedsMacOs_10_14 = 20,
		NeedsMacOs_10_15 = 21,
		NeedsMacOs_11_0 = 22,
		NeedsMacOs_12_0 = 23,
		NeedsMacOs_13_0 = 24,
		NeedsWindows_10 = 25,
		NeedsWindows_11 = 26,
		MacOsUnsupported = 27,
		WindowsUnsupported = 28,
		LegacyUnsupported = 29,
		Dx11Unsupported = 30,
		Dx12Win7Unsupported = 31,
		RemoteDesktopUnsupported = 32,
		WineUnsupported = 33,
		NvapiWineUnsupported = 34,
		AppleGpuUnsupported = 35,
		AmdGpuUnsupported = 36,
		IntelGpuUnsupported = 37,
		NvidiaGpuUnsupported = 38,
		QualcommGpuUnsupported = 39,
		GpuDriver = 40,
		Unknown = 41,
	},
	HolidayCalendarFlags = {
		Alliance = 1,
		Horde = 2,
	},
	HolidayFlags = {
		IsRegionwide = 0x1,
		DontShowInCalendar = 0x2,
		DontDisplayEnd = 0x4,
		DontDisplayBanner = 0x8,
		NotAvailableClientSide = 0x10,
		DurationUseMinutes = 0x20,
		BeginEventOnlyOnStageChange = 0x40,
	},
	IconAndTextWidgetState = {
		Hidden = 0,
		Shown = 1,
		ShownWithDynamicIconFlashing = 2,
		ShownWithDynamicIconNotFlashing = 3,
	},
	IconState = {
		Hidden = 0,
		ShowState1 = 1,
		ShowState2 = 2,
	},
	InputContext = {
		None = 0,
		Keyboard = 1,
		Mouse = 2,
		GamePad = 3,
	},
	InventoryType = {
		IndexNonEquipType = 0,
		IndexHeadType = 1,
		IndexNeckType = 2,
		IndexShoulderType = 3,
		IndexBodyType = 4,
		IndexChestType = 5,
		IndexWaistType = 6,
		IndexLegsType = 7,
		IndexFeetType = 8,
		IndexWristType = 9,
		IndexHandType = 10,
		IndexFingerType = 11,
		IndexTrinketType = 12,
		IndexWeaponType = 13,
		IndexShieldType = 14,
		IndexRangedType = 15,
		IndexCloakType = 16,
		Index2HweaponType = 17,
		IndexBagType = 18,
		IndexTabardType = 19,
		IndexRobeType = 20,
		IndexWeaponmainhandType = 21,
		IndexWeaponoffhandType = 22,
		IndexHoldableType = 23,
		IndexAmmoType = 24,
		IndexThrownType = 25,
		IndexRangedrightType = 26,
		IndexQuiverType = 27,
		IndexRelicType = 28,
		IndexProfessionToolType = 29,
		IndexProfessionGearType = 30,
		IndexEquipablespellOffensiveType = 31,
		IndexEquipablespellUtilityType = 32,
		IndexEquipablespellDefensiveType = 33,
		IndexEquipablespellMobilityType = 34,
	},
	ItemArmorSubclass = {
		Generic = 0,
		Cloth = 1,
		Leather = 2,
		Mail = 3,
		Plate = 4,
		Cosmetic = 5,
		Shield = 6,
		Libram = 7,
		Idol = 8,
		Totem = 9,
		Sigil = 10,
		Relic = 11,
	},
	ItemClass = {
		Consumable = 0,
		Container = 1,
		Weapon = 2,
		Gem = 3,
		Armor = 4,
		Reagent = 5,
		Projectile = 6,
		Tradegoods = 7,
		ItemEnhancement = 8,
		Recipe = 9,
		CurrencyTokenObsolete = 10,
		Quiver = 11,
		Questitem = 12,
		Key = 13,
		PermanentObsolete = 14,
		Miscellaneous = 15,
		Glyph = 16,
		Battlepet = 17,
		WoWToken = 18,
		Profession = 19,
	},
	ItemCommodityStatus = {
		Unknown = 0,
		Item = 1,
		Commodity = 2,
	},
	ItemConsumableSubclass = {
		Generic = 0,
		Potion = 1,
		Elixir = 2,
		Scroll = 3,
		Fooddrink = 4,
		Itemenhancement = 5,
		Bandage = 6,
		Other = 7,
	},
	ItemCreationContext = {
		None = 0,
		DungeonNormal = 1,
		DungeonHeroic = 2,
		RaidNormal = 3,
		RaidFinder = 4,
		RaidHeroic = 5,
		RaidMythic = 6,
		PvPUnranked_1 = 7,
		PvPRanked_1 = 8,
		ScenarioNormal = 9,
		ScenarioHeroic = 10,
		QuestReward = 11,
		Store = 12,
		TradeSkill = 13,
		Vendor = 14,
		BlackMarket = 15,
		ChallengeMode_1 = 16,
		DungeonLevelUp_1 = 17,
		DungeonLevelUp_2 = 18,
		DungeonLevelUp_3 = 19,
		DungeonLevelUp_4 = 20,
		ForceNone = 21,
		Timewalker = 22,
		DungeonMythic = 23,
		PvPHonorReward = 24,
		WorldQuest_1 = 25,
		WorldQuest_2 = 26,
		WorldQuest_3 = 27,
		WorldQuest_4 = 28,
		WorldQuest_5 = 29,
		WorldQuest_6 = 30,
		MissionReward_1 = 31,
		MissionReward_2 = 32,
		ChallengeMode_2 = 33,
		ChallengeMode_3 = 34,
		ChallengeModeJackpot = 35,
		WorldQuest_7 = 36,
		WorldQuest_8 = 37,
		PvPRanked_2 = 38,
		PvPRanked_3 = 39,
		PvPRanked_4 = 40,
		PvPUnranked_2 = 41,
		WorldQuest_9 = 42,
		WorldQuest_10 = 43,
		PvPRanked_5 = 44,
		PvPRanked_6 = 45,
		PvPRanked_7 = 46,
		PvPUnranked_3 = 47,
		PvPUnranked_4 = 48,
		PvPUnranked_5 = 49,
		PvPUnranked_6 = 50,
		PvPUnranked_7 = 51,
		PvPRanked_8 = 52,
		WorldQuest_11 = 53,
		WorldQuest_12 = 54,
		WorldQuest_13 = 55,
		PvPRankedJackpot = 56,
		TournamentRealm = 57,
		Relinquished = 58,
		LegendaryForge = 59,
		QuestBonusLoot = 60,
		CharacterBoost_1 = 61,
		CharacterBoost_2 = 62,
		LegendaryCrafting_1 = 63,
		LegendaryCrafting_2 = 64,
		LegendaryCrafting_3 = 65,
		LegendaryCrafting_4 = 66,
		LegendaryCrafting_5 = 67,
		LegendaryCrafting_6 = 68,
		LegendaryCrafting_7 = 69,
		LegendaryCrafting_8 = 70,
		LegendaryCrafting_9 = 71,
		WeeklyRewardsAdditional = 72,
		WeeklyRewardsConcession = 73,
		WorldQuestJackpot = 74,
		NewCharacter = 75,
		WarMode = 76,
		PvPBrawl_1 = 77,
		PvPBrawl_2 = 78,
		Torghast = 79,
		CorpseRecovery = 80,
		WorldBoss = 81,
		RaidNormalExtended = 82,
		RaidFinderExtended = 83,
		RaidHeroicExtended = 84,
		RaidMythicExtended = 85,
		CharacterBoost_3 = 86,
		ChallengeMode_4 = 87,
		PvPRanked_9 = 88,
		RaidNormalExtended_2 = 89,
		RaidFinderExtended_2 = 90,
		RaidHeroicExtended_2 = 91,
		RaidMythicExtended_2 = 92,
		RaidNormalExtended_3 = 93,
		RaidFinderExtended_3 = 94,
		RaidHeroicExtended_3 = 95,
		RaidMythicExtended_3 = 96,
		TemplateCharacter_1 = 97,
		TemplateCharacter_2 = 98,
		TemplateCharacter_3 = 99,
		TemplateCharacter_4 = 100,
	},
	ItemGemColor = {
		Meta = 0x1,
		Red = 0x2,
		Yellow = 0x4,
		Blue = 0x8,
		Hydraulic = 0x10,
		Cogwheel = 0x20,
		Iron = 0x40,
		Blood = 0x80,
		Shadow = 0x100,
		Fel = 0x200,
		Arcane = 0x400,
		Frost = 0x800,
		Fire = 0x1000,
		Water = 0x2000,
		Life = 0x4000,
		Wind = 0x8000,
		Holy = 0x10000,
		PunchcardRed = 0x20000,
		PunchcardYellow = 0x40000,
		PunchcardBlue = 0x80000,
		DominationBlood = 0x100000,
		DominationFrost = 0x200000,
		DominationUnholy = 0x400000,
		Cypher = 0x800000,
		Tinker = 0x1000000,
	},
	ItemGemSubclass = {
		Intellect = 0,
		Agility = 1,
		Strength = 2,
		Stamina = 3,
		Spirit = 4,
		Criticalstrike = 5,
		Mastery = 6,
		Haste = 7,
		Versatility = 8,
		Other = 9,
		Multiplestats = 10,
		Artifactrelic = 11,
	},
	ItemMiscellaneousSubclass = {
		Junk = 0,
		Reagent = 1,
		CompanionPet = 2,
		Holiday = 3,
		Other = 4,
		Mount = 5,
		MountEquipment = 6,
	},
	ItemModification = {
		TransmogrifyItemModifiedAppearanceIDSpecAll = 0,
		TransmogrifyItemModifiedAppearanceIDSpec_0 = 1,
		IncrementLevelObsolete = 2,
		BattlePetSpecies = 3,
		BattlePetBreed = 4,
		BattlePetLevel = 5,
		BattlePetCreaturedisplayid = 6,
		TransmogrifyOverrideEnchantVisualIDSpecAll = 7,
		ArtifactAppearanceID = 8,
		TimewalkerLevel = 9,
		TransmogrifyOverrideEnchantVisualIDSpec_0 = 10,
		TransmogrifyItemModifiedAppearanceIDSpec_1 = 11,
		TransmogrifyOverrideEnchantVisualIDSpec_1 = 12,
		TransmogrifyItemModifiedAppearanceIDSpec_2 = 13,
		TransmogrifyOverrideEnchantVisualIDSpec_2 = 14,
		TransmogrifyItemModifiedAppearanceIDSpec_3 = 15,
		TransmogrifyOverrideEnchantVisualIDSpec_3 = 16,
		KeystoneMapChallengeModeID = 17,
		KeystonePowerLevel = 18,
		KeystoneAffix0 = 19,
		KeystoneAffix01 = 20,
		KeystoneAffix02 = 21,
		KeystoneAffix03 = 22,
		LegionArtifactKnowledgeObsolete = 23,
		ArtifactTier = 24,
		TransmogrifyItemModifiedAppearanceIDSpec_4 = 25,
		PvPRating = 26,
		TransmogrifyOverrideEnchantVisualIDSpec_4 = 27,
		ContentTuningID = 28,
		ChangeModifiedCraftingStat_1 = 29,
		ChangeModifiedCraftingStat_2 = 30,
		TransmogrifySecondaryItemModifiedAppearanceIDSpecAll = 31,
		TransmogrifySecondaryItemModifiedAppearanceIDSpec_0 = 32,
		TransmogrifySecondaryItemModifiedAppearanceIDSpec_1 = 33,
		TransmogrifySecondaryItemModifiedAppearanceIDSpec_2 = 34,
		TransmogrifySecondaryItemModifiedAppearanceIDSpec_3 = 35,
		TransmogrifySecondaryItemModifiedAppearanceIDSpec_4 = 36,
		SoulbindConduitRank = 37,
		CraftingQualityID = 38,
		CraftingSkillLineAbilityID = 39,
		CraftingDataID = 40,
		CraftingSkillReagents = 41,
		CraftingSkillWatermark = 42,
		CraftingReagentSlot_0 = 43,
		CraftingReagentSlot_1 = 44,
		CraftingReagentSlot_2 = 45,
		CraftingReagentSlot_3 = 46,
		CraftingReagentSlot_4 = 47,
		CraftingReagentSlot_5 = 48,
		CraftingReagentSlot_6 = 49,
		CraftingReagentSlot_7 = 50,
		CraftingReagentSlot_8 = 51,
		CraftingReagentSlot_9 = 52,
	},
	ItemProfessionSubclass = {
		Blacksmithing = 0,
		Leatherworking = 1,
		Alchemy = 2,
		Herbalism = 3,
		Cooking = 4,
		Mining = 5,
		Tailoring = 6,
		Engineering = 7,
		Enchanting = 8,
		Fishing = 9,
		Skinning = 10,
		Jewelcrafting = 11,
		Inscription = 12,
		Archaeology = 13,
	},
	ItemQuality = {
		Poor = 0,
		Common = 1,
		Uncommon = 2,
		Rare = 3,
		Epic = 4,
		Legendary = 5,
		Artifact = 6,
		Heirloom = 7,
		WoWToken = 8,
	},
	ItemReagentSubclass = {
		Reagent = 0,
		Keystone = 1,
		ContextToken = 2,
	},
	ItemRecipeSubclass = {
		Book = 0,
		Leatherworking = 1,
		Tailoring = 2,
		Engineering = 3,
		Blacksmithing = 4,
		Cooking = 5,
		Alchemy = 6,
		FirstAid = 7,
		Enchanting = 8,
		Fishing = 9,
		Jewelcrafting = 10,
		Inscription = 11,
	},
	ItemSlotFilterType = {
		Head = 0,
		Neck = 1,
		Shoulder = 2,
		Cloak = 3,
		Chest = 4,
		Wrist = 5,
		Hand = 6,
		Waist = 7,
		Legs = 8,
		Feet = 9,
		MainHand = 10,
		OffHand = 11,
		Finger = 12,
		Trinket = 13,
		Other = 14,
		NoFilter = 15,
	},
	ItemSocketType = {
		None = 0,
		Meta = 1,
		Red = 2,
		Yellow = 3,
		Blue = 4,
		Hydraulic = 5,
		Cogwheel = 6,
		Prismatic = 7,
		Iron = 8,
		Blood = 9,
		Shadow = 10,
		Fel = 11,
		Arcane = 12,
		Frost = 13,
		Fire = 14,
		Water = 15,
		Life = 16,
		Wind = 17,
		Holy = 18,
		PunchcardRed = 19,
		PunchcardYellow = 20,
		PunchcardBlue = 21,
		Domination = 22,
		Cypher = 23,
		Tinker = 24,
	},
	ItemSoundType = {
		Pickup = 0,
		Drop = 1,
		Use = 2,
		Close = 3,
	},
	ItemSubclassDisplay = {
		HideSubclassInTooltips = 1,
		HideSubclassInAuction = 2,
		ShowItemCount = 4,
	},
	ItemSubclassFlag = {
		WeaponsubclassCanparry = 0x1,
		WeaponsubclassSetfingerseq = 0x2,
		WeaponsubclassIsunarmed = 0x4,
		WeaponsubclassIsrifle = 0x8,
		WeaponsubclassIsthrown = 0x10,
		WeaponsubclassRighthandRanged = 0x20,
		ItemsubclassQuivernotrequired = 0x40,
		WeaponsubclassRanged = 0x80,
		WeaponsubclassDeprecatedReuseMe = 0x100,
		ItemsubclassUsesInvtype = 0x200,
		ArmorsubclassLfgscalingarmor = 0x400,
	},
	ItemTryOnReason = {
		Success = 0,
		WrongRace = 1,
		NotEquippable = 2,
		DataPending = 3,
	},
	ItemWeaponSubclass = {
		Axe1H = 0,
		Axe2H = 1,
		Bows = 2,
		Guns = 3,
		Mace1H = 4,
		Mace2H = 5,
		Polearm = 6,
		Sword1H = 7,
		Sword2H = 8,
		Warglaive = 9,
		Staff = 10,
		Bearclaw = 11,
		Catclaw = 12,
		Unarmed = 13,
		Generic = 14,
		Dagger = 15,
		Thrown = 16,
		Obsolete3 = 17,
		Crossbow = 18,
		Wand = 19,
		Fishingpole = 20,
	},
	Itemclassfilterflags = {
		Consumable = 0x1,
		Container = 0x2,
		Weapon = 0x4,
		Gem = 0x8,
		Armor = 0x10,
		Reagent = 0x20,
		Projectile = 0x40,
		Tradegoods = 0x80,
		ItemEnhancement = 0x100,
		Recipe = 0x200,
		CurrencyTokenObsolete = 0x400,
		Quiver = 0x800,
		Questitemclassfilterflags = 0x1000,
		Key = 0x2000,
		PermanentObsolete = 0x4000,
		Miscellaneous = 0x8000,
		Glyph = 0x10000,
		Battlepet = 0x20000,
	},
	Itemsetflags = {
		Legacy = 1,
		UseItemHistorySetSlots = 2,
		RequiresPvPTalentsActive = 4,
	},
	JailersTowerType = {
		TwistingCorridors = 0,
		SkoldusHalls = 1,
		FractureChambers = 2,
		Soulforges = 3,
		Coldheart = 4,
		Mortregar = 5,
		UpperReaches = 6,
		ArkobanHall = 7,
		TormentChamberJaina = 8,
		TormentChamberThrall = 9,
		TormentChamberAnduin = 10,
		AdamantVaults = 11,
		ForgottenCatacombs = 12,
		Ossuary = 13,
		BossRush = 14,
	},
	LFGEntryPlaystyle = {
		None = 0,
		Standard = 1,
		Casual = 2,
		Hardcore = 3,
	},
	LFGListDisplayType = {
		RoleCount = 0,
		RoleEnumerate = 1,
		ClassEnumerate = 2,
		HideAll = 3,
		PlayerCount = 4,
		Comment = 5,
	},
	LFGListFilter = {
		Recommended = 0x1,
		NotRecommended = 0x2,
		PvE = 0x4,
		PvP = 0x8,
	},
	LanguageFlag = {
		IsExotic = 1,
		HiddenFromPlayer = 2,
	},
	LinkedCurrencyFlags = {
		IgnoreAdd = 1,
		IgnoreSubtract = 2,
		SuppressChatLog = 4,
	},
	LoadConfigResult = {
		Error = 0,
		NoChangesNecessary = 1,
		LoadInProgress = 2,
		Ready = 3,
	},
	LootSlotType = {
		None = 0,
		Item = 1,
		Money = 2,
		Currency = 3,
	},
	MajorFactionFeatureAbility = {
		Generic = 0,
		Fishing = 1,
		Hunts = 2,
	},
	MajorFactionType = {
		None = 0,
		DragonscaleExpedition = 1,
		MaruukCentaur = 2,
		IskaaraTuskarr = 3,
		ValdrakkenAccord = 4,
	},
	ManipulatorEventType = {
		Start = 0,
		Move = 1,
		Complete = 2,
		Delete = 3,
	},
	MapCanvasPosition = {
		None = 0,
		BottomLeft = 1,
		BottomRight = 2,
		TopLeft = 3,
		TopRight = 4,
	},
	MapOverlayDisplayLocation = {
		Default = 0,
		BottomLeft = 1,
		TopLeft = 2,
		BottomRight = 3,
		TopRight = 4,
		Hidden = 5,
	},
	MicroMenuOrder = {
		Default = 0,
		Reverse = 1,
	},
	MicroMenuOrientation = {
		Horizontal = 0,
		Vertical = 1,
	},
	MinimapTrackingFilter = {
		Unfiltered = 0x0,
		Auctioneer = 0x1,
		Banker = 0x2,
		Battlemaster = 0x4,
		TaxiNode = 0x8,
		VenderFood = 0x10,
		Innkeeper = 0x20,
		Mailbox = 0x40,
		TrainerProfession = 0x80,
		VendorReagent = 0x100,
		Repair = 0x200,
		TrivialQuests = 0x400,
		Stablemaster = 0x800,
		Transmogrifier = 0x1000,
		POI = 0x2000,
		Target = 0x4000,
		Focus = 0x8000,
		QuestPoIs = 0x10000,
		Digsites = 0x20000,
		Barber = 0x40000,
		ItemUpgrade = 0x80000,
		VendorPoison = 0x100000,
	},
	ModelSceneSetting = {
		AlignLightToOrbitDelta = 1,
	},
	ModelSceneType = {
		MountJournal = 0,
		PetJournalCard = 1,
		ShopCard = 2,
		EncounterJournal = 3,
		PetJournalLoadout = 4,
		ArtifactTier2 = 5,
		ArtifactTier2ForgingScene = 6,
		ArtifactTier2SlamEffect = 7,
		CommentatorVictoryFanfare = 8,
		ArtifactRelicTalentEffect = 9,
		PvPWarModeOrb = 10,
		PvPWarModeFire = 11,
		PartyPose = 12,
		AzeriteItemLevelUpToast = 13,
		AzeritePowers = 14,
		AzeriteRewardGlow = 15,
		HeartOfAzeroth = 16,
		WorldMapThreat = 17,
		Soulbinds = 18,
		JailersTowerAnimaGlow = 19,
	},
	MountType = {
		Ground = 0,
		Flying = 1,
		Aquatic = 2,
		Dragonriding = 3,
	},
	MountTypeFlag = {
		IsFlyingMount = 1,
		IsAquaticMount = 2,
		IsDragonRidingMount = 4,
	},
	NavigationState = {
		Invalid = 0,
		Occluded = 1,
		InRange = 2,
		Disabled = 3,
	},
	NodeOpFailureReason = {
		None = 0,
		MissingEdgeConnection = 1,
		RequiredForEdge = 2,
		MissingRequiredEdge = 3,
		HasMutuallyExclusiveEdge = 4,
		NotEnoughSourcedCurrencySpent = 5,
		NotEnoughCurrencySpent = 6,
		NotEnoughGoldSpent = 7,
		MissingAchievement = 8,
		MissingQuest = 9,
		WrongSpec = 10,
		WrongSelection = 11,
		MaxRank = 12,
		DataError = 13,
		NotEnoughSourcedCurrency = 14,
		NotEnoughCurrency = 15,
		NotEnoughGold = 16,
		SameSelection = 17,
		NodeNotFound = 18,
		EntryNotFound = 19,
		RequiredForCondition = 20,
		WrongTreeID = 21,
		LevelTooLow = 22,
		TreeFlaggedNoRefund = 23,
		NodeNeverPurchasable = 24,
	},
	PartyRequestJoinRelation = {
		None = 0,
		Friend = 1,
		Guild = 2,
		Club = 3,
		NumPartyRequestJoinRelations = 4,
	},
	PerksVendorCategoryType = {
		Transmog = 1,
		Mount = 2,
		Pet = 3,
		Toy = 5,
		Illusion = 7,
		Transmogset = 8,
	},
	PermanentChatChannelType = {
		None = 0,
		Zone = 1,
		Communities = 2,
		Custom = 3,
	},
	PetBattleQueueStatus = {
		None = 0,
		Queued = 1,
		QueuedUpdate = 2,
		AlreadyQueued = 3,
		JoinFailed = 4,
		JoinFailedSlots = 5,
		JoinFailedJournalLock = 6,
		JoinFailedNeutral = 7,
		MatchAccepted = 8,
		MatchDeclined = 9,
		MatchOpponentDeclined = 10,
		ProposalTimedOut = 11,
		Removed = 12,
		RequeuedAfterInternalError = 13,
		RequeuedAfterOpponentRemoved = 14,
		Matchmaking = 15,
		LostConnection = 16,
		Shutdown = 17,
		Suspended = 18,
		Unsuspended = 19,
		InBattle = 20,
		NoBattlingHere = 21,
	},
	PetJournalError = {
		None = 0,
		PetIsDead = 1,
		JournalIsLocked = 2,
		InvalidFaction = 3,
		NoFavoritesToSummon = 4,
		NoValidRandomSummon = 5,
		InvalidCovenant = 6,
	},
	PetbattleAuraStateFlags = {
		None = 0x0,
		Infinite = 0x1,
		Canceled = 0x2,
		InitDisabled = 0x4,
		CountdownFirstRound = 0x8,
		JustApplied = 0x10,
		RemoveEventHandled = 0x20,
	},
	PetbattleCheatFlags = {
		None = 0,
		AutoPlay = 1,
	},
	PetbattleEffectFlags = {
		None = 0x0,
		InvalidTarget = 0x1,
		Miss = 0x2,
		Crit = 0x4,
		Blocked = 0x8,
		Dodge = 0x10,
		Heal = 0x20,
		Unkillable = 0x40,
		Reflect = 0x80,
		Absorb = 0x100,
		Immune = 0x200,
		Strong = 0x400,
		Weak = 0x800,
		SuccessChain = 0x1000,
		AuraReapply = 0x2000,
	},
	PetbattleEffectType = {
		SetHealth = 0,
		AuraApply = 1,
		AuraCancel = 2,
		AuraChange = 3,
		PetSwap = 4,
		StatusChange = 5,
		SetState = 6,
		SetMaxHealth = 7,
		SetSpeed = 8,
		SetPower = 9,
		TriggerAbility = 10,
		AbilityChange = 11,
		NpcEmote = 12,
		AuraProcessingBegin = 13,
		AuraProcessingEnd = 14,
		ReplacePet = 15,
		OverrideAbility = 16,
		WorldStateUpdate = 17,
	},
	PetbattleEnviros = {
		Pad0 = 0,
		Pad1 = 1,
		Weather = 2,
	},
	PetbattleInputMoveMsgDebugFlag = {
		None = 0,
		DontValidate = 1,
		EnemyCast = 2,
	},
	PetbattleMoveType = {
		Quit = 0,
		Ability = 1,
		Swap = 2,
		Trap = 3,
		FinalRoundOk = 4,
		Pass = 5,
	},
	PetbattlePboid = {
		P0Pet_0 = 0,
		P0Pet_1 = 1,
		P0Pet_2 = 2,
		P1Pet_0 = 3,
		P1Pet_1 = 4,
		P1Pet_2 = 5,
		EnvPad_0 = 6,
		EnvPad_1 = 7,
		EnvWeather = 8,
	},
	PetbattlePetStatus = {
		FlagNone = 0x0,
		FlagTrapped = 0x1,
		Stunned = 0x2,
		SwapOutLocked = 0x4,
		SwapInLocked = 0x8,
	},
	PetbattlePlayer = {
		Player_0 = 0,
		Player_1 = 1,
	},
	PetbattlePlayerInputFlags = {
		None = 0x0,
		TurnInProgress = 0x1,
		AbilityLocked = 0x2,
		SwapLocked = 0x4,
		WaitingForPet = 0x8,
	},
	PetbattleResult = {
		FailUnknown = 0,
		FailNotHere = 1,
		FailNotHereOnTransport = 2,
		FailNotHereUnevenGround = 3,
		FailNotHereObstructed = 4,
		FailNotWhileInCombat = 5,
		FailNotWhileDead = 6,
		FailNotWhileFlying = 7,
		FailTargetInvalid = 8,
		FailTargetOutOfRange = 9,
		FailTargetNotCapturable = 10,
		FailNotATrainer = 11,
		FailDeclined = 12,
		FailInBattle = 13,
		FailInvalidLoadout = 14,
		FailInvalidLoadoutAllDead = 15,
		FailInvalidLoadoutNoneSlotted = 16,
		FailNoJournalLock = 17,
		FailWildPetTapped = 18,
		FailRestrictedAccount = 19,
		FailOpponentNotAvailable = 20,
		FailLogout = 21,
		FailDisconnect = 22,
		Success = 23,
	},
	PetbattleSlot = {
		Slot_0 = 0,
		Slot_1 = 1,
		Slot_2 = 2,
	},
	PetbattleSlotAbility = {
		Ability_0 = 0,
		Ability_1 = 1,
		Ability_2 = 2,
	},
	PetbattleSlotResult = {
		Success = 0,
		SlotLocked = 1,
		SlotEmpty = 2,
		NoTracker = 3,
		NoSpeciesRec = 4,
		CantBattle = 5,
		Revoked = 6,
		Dead = 7,
		NoPet = 8,
	},
	PetbattleState = {
		Created = 0,
		WaitingPreBattle = 1,
		RoundInProgress = 2,
		WaitingForFrontPets = 3,
		CreatedFailed = 4,
		FinalRound = 5,
		Finished = 6,
	},
	PetbattleTrapstatus = {
		Invalid = 0,
		CanTrap = 1,
		CantTrapNewbie = 2,
		CantTrapPetDead = 3,
		CantTrapPetHealth = 4,
		CantTrapNoRoomInJournal = 5,
		CantTrapPetNotCapturable = 6,
		CantTrapTrainerBattle = 7,
		CantTrapTwice = 8,
	},
	PetbattleType = {
		PvE = 0,
		PvP = 1,
		Lfpb = 2,
		Npc = 3,
	},
	PhaseReason = {
		Phasing = 0,
		Sharding = 1,
		WarMode = 2,
		ChromieTime = 3,
	},
	PlayerChoiceRarity = {
		Common = 0,
		Uncommon = 1,
		Rare = 2,
		Epic = 3,
	},
	PlayerClubRequestStatus = {
		None = 0,
		Pending = 1,
		AutoApproved = 2,
		Declined = 3,
		Approved = 4,
		Joined = 5,
		JoinedAnother = 6,
		Canceled = 7,
	},
	PlayerCurrencyFlags = {
		Incremented = 1,
		Loading = 2,
	},
	PlayerCurrencyFlagsDbFlags = {
		IgnoreMaxQtyOnload = 0x1,
		Reuse1 = 0x2,
		InBackpack = 0x4,
		UnusedInUI = 0x8,
		Reuse2 = 0x10,
	},
	PlayerInteractionType = {
		None = 0,
		TradePartner = 1,
		Item = 2,
		Gossip = 3,
		QuestGiver = 4,
		Merchant = 5,
		TaxiNode = 6,
		Trainer = 7,
		Banker = 8,
		AlliedRaceDetailsGiver = 9,
		GuildBanker = 10,
		Registrar = 11,
		Vendor = 12,
		PetitionVendor = 13,
		TabardVendor = 14,
		TalentMaster = 15,
		SpecializationMaster = 16,
		MailInfo = 17,
		SpiritHealer = 18,
		AreaSpiritHealer = 19,
		Binder = 20,
		Auctioneer = 21,
		StableMaster = 22,
		BattleMaster = 23,
		Transmogrifier = 24,
		LFGDungeon = 25,
		VoidStorageBanker = 26,
		BlackMarketAuctioneer = 27,
		AdventureMap = 28,
		WorldMap = 29,
		GarrArchitect = 30,
		GarrTradeskill = 31,
		GarrMission = 32,
		ShipmentCrafter = 33,
		GarrRecruitment = 34,
		GarrTalent = 35,
		Trophy = 36,
		PlayerChoice = 37,
		ArtifactForge = 38,
		ObliterumForge = 39,
		ScrappingMachine = 40,
		ContributionCollector = 41,
		AzeriteRespec = 42,
		IslandQueue = 43,
		ItemInteraction = 44,
		ChromieTime = 45,
		CovenantPreview = 46,
		AnimaDiversion = 47,
		LegendaryCrafting = 48,
		WeeklyRewards = 49,
		Soulbind = 50,
		CovenantSanctum = 51,
		NewPlayerGuide = 52,
		ItemUpgrade = 53,
		AdventureJournal = 54,
		Renown = 55,
		AzeriteForge = 56,
		PerksProgramVendor = 57,
		ProfessionsCraftingOrder = 58,
		Professions = 59,
		ProfessionsCustomerOrder = 60,
		TraitSystem = 61,
		BarbersChoice = 62,
		JailersTowerBuffs = 63,
		MajorFactionRenown = 64,
	},
	PlayerMentorshipApplicationResult = {
		Success = 0,
		AlreadyMentor = 1,
		Ineligible = 2,
	},
	PlayerMentorshipStatus = {
		None = 0,
		Newcomer = 1,
		Mentor = 2,
	},
	PointsModifierSourceType = {
		PlayerLevel = 0,
		SkillRank = 1,
		ProgressiveEventMissCount = 2,
		ProgressiveEventItemWinCount = 3,
		NumLooters = 4,
		BaseItemLevel = 5,
		LootLevel = 6,
		InstanceGroupSize = 7,
		QuestItemGroupMissCount = 8,
		TreasureItemPvalue = 9,
		FollowerLevelInBuilding = 10,
		FollowerQualityInBuilding = 11,
		NumGroupFriends = 12,
		FollowerLevelForCurrentShipment = 13,
		FollowerQualityForCurrentShipment = 14,
		PvPBracketRatingSpecific = 15,
		ChallengeModeLevel = 16,
		CurrencyMaxDelta = 17,
		WorldStateValue = 18,
		PlayerKeystoneLevel = 19,
		PlayerCondition = 20,
		PassesTreasureTrackingQuestEligibility = 21,
		PvPBracketRatingCurrentInstance = 22,
		PvPTeamSize = 23,
		ItemLevelHighWaterMarkAverage = 24,
		ProgressiveEventNumWinsForLootSpec = 25,
		ProgressiveEventNumRemainingForLootSpec = 26,
		WorldStateExpression = 27,
		ProgressiveEventNumRemainingForClass = 28,
		CreatureClassification = 29,
		HonorEarnedThisPvPMatch = 30,
		NumTappers = 31,
		PvPJackpotTier = 32,
		PlayerLevelContentTuningMax = 33,
		SalvagedItemIsCloth = 34,
		SalvagedItemIsLeather = 35,
		SalvagedItemIsMail = 36,
		SalvagedItemIsPlate = 37,
		SalvagedItemIsMisc = 38,
		QuestExpansionID = 39,
		Reserved_2 = 40,
		JailersTowerActiveFloorDifficulty = 41,
		NumLootSourceAuraStacks = 42,
		HasLegendaryCloakUpdgradeAvailable = 43,
		ObjectLevel = 44,
		PercentThroughContentTuning = 45,
		PvPTier = 46,
		CurrencyQuantity = 47,
		AreaGroup = 48,
		ObjectLabelID = 49,
		WeeklyMythicPlusCount = 50,
		PercentThroughExpansion = 51,
		AutoMissionScalar = 52,
		RenownCatchup = 53,
		RenownRapidCatchup = 54,
		ParagonLevel = 55,
		NumPlayersThatGainedDungeonScore = 56,
		ProfessionQualityLevel = 57,
		CraftSkill = 58,
		NumWeeklyRewardsThresholdsEarned = 59,
		SalvagedItemLevel = 60,
		ProfessionRatingFinessePercent = 61,
		ProfessionRatingPerceptionPercent = 62,
		ProfessionTraitRanksByLabel = 63,
	},
	PowerType = {
		HealthCost = -2,
		None = -1,
		Mana = 0,
		Rage = 1,
		Focus = 2,
		Energy = 3,
		ComboPoints = 4,
		Runes = 5,
		RunicPower = 6,
		SoulShards = 7,
		LunarPower = 8,
		HolyPower = 9,
		Alternate = 10,
		Maelstrom = 11,
		Chi = 12,
		Insanity = 13,
		Obsolete = 14,
		Obsolete2 = 15,
		ArcaneCharges = 16,
		Fury = 17,
		Pain = 18,
		Essence = 19,
		RuneBlood = 20,
		RuneFrost = 21,
		RuneUnholy = 22,
		NumPowerTypes = 23,
	},
	ProfTraitPerkNodeFlags = {
		UnlocksSubpath = 1,
		IsMajorBonus = 2,
	},
	Profession = {
		FirstAid = 0,
		Blacksmithing = 1,
		Leatherworking = 2,
		Alchemy = 3,
		Herbalism = 4,
		Cooking = 5,
		Mining = 6,
		Tailoring = 7,
		Engineering = 8,
		Enchanting = 9,
		Fishing = 10,
		Skinning = 11,
		Jewelcrafting = 12,
		Inscription = 13,
		Archaeology = 14,
	},
	ProfessionActionType = {
		Craft = 0,
		Gather = 1,
	},
	ProfessionEffect = {
		Skill = 0,
		StatInspiration = 1,
		StatResourcefulness = 2,
		StatFinesse = 3,
		StatDeftness = 4,
		StatPerception = 5,
		StatCraftingSpeed = 6,
		StatMulticraft = 7,
		UnlockReagentSlot = 8,
		ModInspiration = 9,
		ModResourcefulness = 10,
		ModFinesse = 11,
		ModDeftness = 12,
		ModPerception = 13,
		ModCraftingSpeed = 14,
		ModMulticraft = 15,
		ModUnused_1 = 16,
		ModUnused_2 = 17,
		ModCraftExtraQuantity = 18,
		ModGatherExtraQuantity = 19,
		ModCraftCritSize = 20,
		ModCraftReductionQuantity = 21,
		DecreaseDifficulty = 22,
		IncreaseDifficulty = 23,
		ModSkillGain = 24,
		AccumulateRanksByLabel = 25,
	},
	ProfessionRating = {
		Inspiration = 0,
		Resourcefulness = 1,
		Finesse = 2,
		Deftness = 3,
		Perception = 4,
		CraftingSpeed = 5,
		Multicraft = 6,
		Unused_1 = 7,
		Unused_2 = 8,
	},
	ProfessionRatingType = {
		Craft = 0,
		Gather = 1,
	},
	ProfessionsSpecPathState = {
		Locked = 0,
		Progressing = 1,
		Completed = 2,
	},
	ProfessionsSpecPerkState = {
		Unearned = 0,
		Pending = 1,
		Earned = 2,
	},
	ProfessionsSpecTabState = {
		Locked = 0,
		Unlocked = 1,
		Unlockable = 2,
	},
	PvPFaction = {
		Horde = 0,
		Alliance = 1,
	},
	PvPMatchState = {
		Inactive = 0,
		Active = 1,
		Complete = 2,
	},
	PvPUnitClassification = {
		FlagCarrierHorde = 0,
		FlagCarrierAlliance = 1,
		FlagCarrierNeutral = 2,
		CartRunnerHorde = 3,
		CartRunnerAlliance = 4,
		AssassinHorde = 5,
		AssassinAlliance = 6,
		OrbCarrierBlue = 7,
		OrbCarrierGreen = 8,
		OrbCarrierOrange = 9,
		OrbCarrierPurple = 10,
	},
	QuestFrequency = {
		Default = 0,
		Daily = 1,
		Weekly = 2,
	},
	QuestLineFloorLocation = {
		Above = 0,
		Below = 1,
		Same = 2,
	},
	QuestPOIQuestTypes = {
		Normal = 1,
		Campaign = 2,
		Calling = 3,
	},
	QuestSessionCommand = {
		None = 0,
		Start = 1,
		Stop = 2,
		SessionActiveNoCommand = 3,
	},
	QuestSessionResult = {
		Ok = 0,
		NotInParty = 1,
		InvalidOwner = 2,
		AlreadyActive = 3,
		NotActive = 4,
		InRaid = 5,
		OwnerRefused = 6,
		Timeout = 7,
		Disabled = 8,
		Started = 9,
		Stopped = 10,
		Joined = 11,
		Left = 12,
		OwnerLeft = 13,
		ReadyCheckFailed = 14,
		PartyDestroyed = 15,
		MemberTimeout = 16,
		AlreadyMember = 17,
		NotOwner = 18,
		AlreadyOwner = 19,
		AlreadyJoined = 20,
		NotMember = 21,
		Busy = 22,
		JoinRejected = 23,
		Logout = 24,
		Empty = 25,
		QuestNotCompleted = 26,
		Resync = 27,
		Restricted = 28,
		InPetBattle = 29,
		InvalidPublicParty = 30,
		Unknown = 31,
		InCombat = 32,
		MemberInCombat = 33,
		RestrictedCrossFaction = 34,
	},
	QuestTag = {
		Group = 1,
		PvP = 41,
		Raid = 62,
		Dungeon = 81,
		Legendary = 83,
		Heroic = 85,
		Raid10 = 88,
		Raid25 = 89,
		Scenario = 98,
		Account = 102,
		CombatAlly = 266,
	},
	QuestTagType = {
		Tag = 0,
		Profession = 1,
		Normal = 2,
		PvP = 3,
		PetBattle = 4,
		Bounty = 5,
		Dungeon = 6,
		Invasion = 7,
		Raid = 8,
		Contribution = 9,
		RatedReward = 10,
		InvasionWrapper = 11,
		FactionAssault = 12,
		Islands = 13,
		Threat = 14,
		CovenantCalling = 15,
		DragonRiderRacing = 16,
	},
	QuestWatchType = {
		Automatic = 0,
		Manual = 1,
	},
	RafLinkType = {
		None = 0,
		Recruit = 1,
		Friend = 2,
		Both = 3,
	},
	RafRecruitActivityState = {
		Incomplete = 0,
		Complete = 1,
		RewardClaimed = 2,
	},
	RafRecruitSubStatus = {
		Trial = 0,
		Active = 1,
		Inactive = 2,
	},
	RafRewardType = {
		Pet = 0,
		Mount = 1,
		Appearance = 2,
		Title = 3,
		GameTime = 4,
		AppearanceSet = 5,
		Illusion = 6,
		Invalid = 7,
	},
	RaidGroupDisplayType = {
		SeparateGroupsVertical = 0,
		SeparateGroupsHorizontal = 1,
		CombineGroupsVertical = 2,
		CombineGroupsHorizontal = 3,
	},
	RcoCloseReason = {
		RcoCloseFulfill = 0,
		RcoCloseExpire = 1,
		RcoCloseCancel = 2,
		RcoCloseReject = 3,
		RcoCloseGmCancel = 4,
		RcoCloseCrafterFulfill = 5,
		RcoCloseInvalid = 6,
	},
	RecipeRequirementType = {
		SpellFocus = 0,
		Totem = 1,
		Area = 2,
	},
	RelativeContentDifficulty = {
		Trivial = 0,
		Easy = 1,
		Fair = 2,
		Difficult = 3,
		Impossible = 4,
	},
	ReportMajorCategory = {
		InappropriateCommunication = 0,
		GameplaySabotage = 1,
		Cheating = 2,
		InappropriateName = 3,
	},
	ReportMinorCategory = {
		TextChat = 0x1,
		Boosting = 0x2,
		Spam = 0x4,
		Afk = 0x8,
		IntentionallyFeeding = 0x10,
		BlockingProgress = 0x20,
		Hacking = 0x40,
		Botting = 0x80,
		Advertisement = 0x100,
		BTag = 0x200,
		GroupName = 0x400,
		CharacterName = 0x800,
		GuildName = 0x1000,
		Description = 0x2000,
		Name = 0x4000,
	},
	ReportType = {
		Chat = 0,
		InWorld = 1,
		ClubFinderPosting = 2,
		ClubFinderApplicant = 3,
		GroupFinderPosting = 4,
		GroupFinderApplicant = 5,
		ClubMember = 6,
		GroupMember = 7,
		Friend = 8,
		Pet = 9,
		BattlePet = 10,
		Calendar = 11,
		Mail = 12,
		PvP = 13,
		PvPScoreboard = 14,
		PvPGroupMember = 15,
	},
	RuneforgePowerFilter = {
		All = 0,
		Relevant = 1,
		Available = 2,
		Unavailable = 3,
	},
	RuneforgePowerState = {
		Available = 0,
		Unavailable = 1,
		Invalid = 2,
	},
	ScriptedAnimationBehavior = {
		None = 0,
		TargetShake = 1,
		TargetKnockBack = 2,
		SourceRecoil = 3,
		SourceCollideWithTarget = 4,
		UIParentShake = 5,
	},
	ScriptedAnimationFlags = {
		UseTargetAsSource = 1,
	},
	ScriptedAnimationTrajectory = {
		AtSource = 0,
		AtTarget = 1,
		Straight = 2,
		CurveLeft = 3,
		CurveRight = 4,
		CurveRandom = 5,
		HalfwayBetween = 6,
	},
	ScrubStringFlags = {
		None = 0,
		TruncateNewLines = 1,
		AllowBarCodes = 2,
		StripControlCodes = 4,
	},
	SelfResurrectOptionType = {
		Spell = 0,
		Item = 1,
	},
	SharedStringFlag = {
		InternalOnly = 1,
	},
	SkinningState = {
		None = 0,
		Reserved = 1,
		Skinning = 2,
		Looting = 3,
		Skinned = 4,
	},
	SlotRegion = {
		Invalid = 0,
		PlayerEquip = 1,
		PlayerInv = 2,
		Bank = 3,
		ReagentBank = 4,
	},
	SoftTargetEnableFlags = {
		None = 0,
		Gamepad = 1,
		Kbm = 2,
		Any = 3,
	},
	SortPlayersBy = {
		Role = 0,
		Group = 1,
		Alphabetical = 2,
	},
	SoulbindConduitFlags = {
		VisibleToGetallsoulbindconduitScript = 1,
	},
	SoulbindConduitInstallResult = {
		Success = 0,
		InvalidItem = 1,
		InvalidConduit = 2,
		InvalidTalent = 3,
		DuplicateConduit = 4,
		ForgeNotInProximity = 5,
		SocketNotEmpty = 6,
	},
	SoulbindConduitTransactionType = {
		Install = 0,
		Uninstall = 1,
	},
	SoulbindConduitType = {
		Finesse = 0,
		Potency = 1,
		Endurance = 2,
		Flex = 3,
	},
	SoulbindNodeState = {
		Unavailable = 0,
		Unselected = 1,
		Selectable = 2,
		Selected = 3,
	},
	SpellDisplayBorderColor = {
		None = 0,
		Black = 1,
		White = 2,
		Red = 3,
		Yellow = 4,
		Orange = 5,
		Purple = 6,
		Green = 7,
		Blue = 8,
	},
	SpellDisplayIconDisplayType = {
		Buff = 0,
		Debuff = 1,
		Circular = 2,
		NoBorder = 3,
	},
	SpellDisplayIconSizeType = {
		Small = 0,
		Medium = 1,
		Large = 2,
	},
	SpellDisplayTextShownStateType = {
		Shown = 0,
		Hidden = 1,
	},
	SplashScreenType = {
		WhatsNew = 0,
		SeasonRollOver = 1,
	},
	StatusBarColorTintValue = {
		None = 0,
		Black = 1,
		White = 2,
		Red = 3,
		Yellow = 4,
		Orange = 5,
		Purple = 6,
		Green = 7,
		Blue = 8,
	},
	StatusBarOverrideBarTextShownType = {
		Never = 0,
		Always = 1,
		OnlyOnMouseover = 2,
		OnlyNotOnMouseover = 3,
	},
	StatusBarValueTextType = {
		Hidden = 0,
		Percentage = 1,
		Value = 2,
		Time = 3,
		TimeShowOneLevelOnly = 4,
		ValueOverMax = 5,
		ValueOverMaxNormalized = 6,
	},
	SubscriptionInterstitialResponseType = {
		Clicked = 0,
		Closed = 1,
		WebRedirect = 2,
	},
	SubscriptionInterstitialType = {
		Standard = 0,
		LeftNpeArea = 1,
		MaxLevel = 2,
	},
	SummonStatus = {
		None = 0,
		Pending = 1,
		Accepted = 2,
		Declined = 3,
	},
	SuperTrackingType = {
		Quest = 0,
		UserWaypoint = 1,
		Corpse = 2,
		Scenario = 3,
	},
	TooltipComparisonMethod = {
		Single = 0,
		WithBothHands = 1,
		WithBagMainHandItem = 2,
		WithBagOffHandItem = 3,
	},
	TooltipDataItemBinding = {
		Quest = 0,
		Account = 1,
		BnetAccount = 2,
		Soulbound = 3,
		BindToAccount = 4,
		BindToBnetAccount = 5,
		BindOnPickup = 6,
		BindOnEquip = 7,
		BindOnUse = 8,
	},
	TooltipDataLineType = {
		None = 0,
		Blank = 1,
		UnitName = 2,
		GemSocket = 3,
		AzeriteEssenceSlot = 4,
		AzeriteEssencePower = 5,
		LearnableSpell = 6,
		UnitThreat = 7,
		QuestObjective = 8,
		AzeriteItemPowerDescription = 9,
		RuneforgeLegendaryPowerDescription = 10,
		SellPrice = 11,
		ProfessionCraftingQuality = 12,
		SpellName = 13,
		CurrencyTotal = 14,
		ItemEnchantmentPermanent = 15,
		UnitOwner = 16,
		QuestTitle = 17,
		QuestPlayer = 18,
		NestedBlock = 19,
		ItemBinding = 20,
		RestrictedRaceClass = 21,
		RestrictedFaction = 22,
		RestrictedSkill = 23,
		RestrictedPvPMedal = 24,
		RestrictedReputation = 25,
		RestrictedSpellKnown = 26,
		RestrictedLevel = 27,
		EquipSlot = 28,
		ItemName = 29,
	},
	TooltipDataType = {
		Item = 0,
		Spell = 1,
		Unit = 2,
		Corpse = 3,
		Object = 4,
		Currency = 5,
		BattlePet = 6,
		UnitAura = 7,
		AzeriteEssence = 8,
		CompanionPet = 9,
		Mount = 10,
		PetAction = 11,
		Achievement = 12,
		EnhancedConduit = 13,
		EquipmentSet = 14,
		InstanceLock = 15,
		PvPBrawl = 16,
		RecipeRankInfo = 17,
		Totem = 18,
		Toy = 19,
		CorruptionCleanser = 20,
		MinimapMouseover = 21,
		Flyout = 22,
		Quest = 23,
		QuestPartyProgress = 24,
		Macro = 25,
		Debug = 26,
	},
	TooltipSide = {
		Left = 0,
		Right = 1,
		Top = 2,
		Bottom = 3,
	},
	TooltipTextureAnchor = {
		LeftTop = 0,
		LeftCenter = 1,
		LeftBottom = 2,
		RightTop = 3,
		RightCenter = 4,
		RightBottom = 5,
		All = 6,
	},
	TooltipTextureRelativeRegion = {
		LeftLine = 0,
		RightLine = 1,
	},
	TrackedSpellCategory = {
		Offensive = 0,
		Defensive = 1,
		Debuff = 2,
		RacialAbility = 3,
		Count = 4,
	},
	TradeskillOrderDuration = {
		Short = 1,
		Medium = 2,
		Long = 3,
	},
	TradeskillOrderRecipient = {
		Public = 1,
		Guild = 2,
		Private = 3,
	},
	TradeskillOrderStatus = {
		Unclaimed = 1,
		Started = 2,
		Completed = 3,
		Expired = 4,
	},
	TradeskillRecipeType = {
		Item = 1,
		Salvage = 2,
		Enchant = 3,
		Recraft = 4,
		Gathering = 5,
	},
	TradeskillRelativeDifficulty = {
		Optimal = 0,
		Medium = 1,
		Easy = 2,
		Trivial = 3,
	},
	TradeskillSlotDataType = {
		Reagent = 1,
		ModifiedReagent = 2,
		Currency = 3,
	},
	TraitCombatConfigFlags = {
		ActiveForSpec = 1,
		StarterBuild = 2,
		SharedActionBars = 4,
	},
	TraitCondFlag = {
		IsGate = 1,
		IsAlwaysMet = 2,
		IsSufficient = 4,
	},
	TraitConditionType = {
		Available = 0,
		Visible = 1,
		Granted = 2,
		Increased = 3,
	},
	TraitConfigDbState = {
		Ready = 0,
		Created = 1,
		Removed = 2,
		Deleted = 3,
	},
	TraitConfigType = {
		Invalid = 0,
		Combat = 1,
		Profession = 2,
		Generic = 3,
	},
	TraitCurrencyFlag = {
		ShowQuantityAsSpent = 0x1,
		TraitSourcedShowMax = 0x2,
		UseClassIcon = 0x4,
		UseSpecIcon = 0x8,
	},
	TraitCurrencyType = {
		Gold = 0,
		CurrencyTypesBased = 1,
		TraitSourced = 2,
	},
	TraitDefinitionSubType = {
		DragonflightRed = 0,
		DragonflightBlue = 1,
		DragonflightGreen = 2,
		DragonflightBronze = 3,
		DragonflightBlack = 4,
	},
	TraitEdgeType = {
		VisualOnly = 0,
		DeprecatedRankConnection = 1,
		SufficientForAvailability = 2,
		RequiredForAvailability = 3,
		MutuallyExclusive = 4,
		DeprecatedSelectionOption = 5,
	},
	TraitEdgeVisualStyle = {
		None = 0,
		Straight = 1,
	},
	TraitNodeEntryType = {
		SpendHex = 0,
		SpendSquare = 1,
		SpendCircle = 2,
		SpendSmallCircle = 3,
		DeprecatedSelect = 4,
		DragAndDrop = 5,
		SpendDiamond = 6,
		ProfPath = 7,
		ProfPerk = 8,
		ProfPathUnlock = 9,
	},
	TraitNodeFlag = {
		ShowMultipleIcons = 0x1,
		NeverPurchasable = 0x2,
		TestPositionLocked = 0x4,
		TestGridPositioned = 0x8,
	},
	TraitNodeGroupFlag = {
		AvailableByDefault = 1,
	},
	TraitNodeType = {
		Single = 0,
		Tiered = 1,
		Selection = 2,
	},
	TraitPointsOperationType = {
		None = -1,
		Set = 0,
		Multiply = 1,
	},
	TraitSystemFlag = {
		AllowMultipleLoadoutsPerTree = 1,
	},
	TraitTreeFlag = {
		CannotRefund = 1,
		HideSingleRankNumbers = 2,
	},
	TransmogCameraVariation = {
		None = 0,
		CloakBackpack = 1,
		RightShoulder = 1,
	},
	TransmogCollectionType = {
		None = 0,
		Head = 1,
		Shoulder = 2,
		Back = 3,
		Chest = 4,
		Shirt = 5,
		Tabard = 6,
		Wrist = 7,
		Hands = 8,
		Waist = 9,
		Legs = 10,
		Feet = 11,
		Wand = 12,
		OneHAxe = 13,
		OneHSword = 14,
		OneHMace = 15,
		Dagger = 16,
		Fist = 17,
		Shield = 18,
		Holdable = 19,
		TwoHAxe = 20,
		TwoHSword = 21,
		TwoHMace = 22,
		Staff = 23,
		Polearm = 24,
		Bow = 25,
		Gun = 26,
		Crossbow = 27,
		Warglaives = 28,
		Paired = 29,
	},
	TransmogIllisionFlags = {
		HideUntilCollected = 1,
		PlayerConditionGrantsOnLogin = 2,
	},
	TransmogModification = {
		Main = 0,
		Secondary = 1,
	},
	TransmogPendingType = {
		Apply = 0,
		Revert = 1,
		ToggleOn = 2,
		ToggleOff = 3,
	},
	TransmogSearchType = {
		Items = 1,
		BaseSets = 2,
		UsableSets = 3,
	},
	TransmogSlot = {
		Head = 0,
		Shoulder = 1,
		Back = 2,
		Chest = 3,
		Body = 4,
		Tabard = 5,
		Wrist = 6,
		Hand = 7,
		Waist = 8,
		Legs = 9,
		Feet = 10,
		Mainhand = 11,
		Offhand = 12,
	},
	TransmogSource = {
		None = 0,
		JournalEncounter = 1,
		Quest = 2,
		Vendor = 3,
		WorldDrop = 4,
		HiddenUntilCollected = 5,
		CantCollect = 6,
		Achievement = 7,
		Profession = 8,
		NotValidForTransmog = 9,
	},
	TransmogType = {
		Appearance = 0,
		Illusion = 1,
	},
	TransmogUseErrorType = {
		None = 0,
		PlayerCondition = 1,
		Skill = 2,
		Ability = 3,
		Faction = 4,
		Holiday = 5,
		HotRecheckFailed = 6,
	},
	TtsBoolSetting = {
		PlaySoundSeparatingChatLineBreaks = 0,
		AddCharacterNameToSpeech = 1,
		PlayActivitySoundWhenNotFocused = 2,
		AlternateSystemVoice = 3,
		NarrateMyMessages = 4,
	},
	TtsVoiceType = {
		Standard = 0,
		Alternate = 1,
	},
	UICursorType = {
		Default = 0,
		Item = 1,
		Money = 2,
		Spell = 3,
		PetAction = 4,
		Merchant = 5,
		ActionBar = 6,
		Macro = 7,
		AmmoObsolete = 9,
		Pet = 10,
		GuildBank = 11,
		GuildBankMoney = 12,
		EquipmentSet = 13,
		Currency = 14,
		Flyout = 15,
		VoidItem = 16,
		BattlePet = 17,
		Mount = 18,
		Toy = 19,
		ConduitCollectionItem = 20,
		PerksProgramVendorItem = 21,
	},
	UIFrameType = {
		JailersTowerBuffs = 0,
	},
	UIItemInteractionFlags = {
		DisplayWithInset = 0x1,
		ConfirmationHasDelay = 0x2,
		ConversionMode = 0x4,
		ClickShowsFlyout = 0x8,
		AddCurrency = 0x10,
		UsesCharges = 0x20,
	},
	UIItemInteractionType = {
		None = 0,
		CastSpell = 1,
		CleanseCorruption = 2,
		RunecarverScrapping = 3,
		ItemConversion = 4,
	},
	UIMapFlag = {
		NoHighlight = 0x1,
		ShowOverlays = 0x2,
		ShowTaxiNodes = 0x4,
		GarrisonMap = 0x8,
		FallbackToParentMap = 0x10,
		NoHighlightTexture = 0x20,
		ShowTaskObjectives = 0x40,
		NoWorldPositions = 0x80,
		HideArchaeologyDigs = 0x100,
		Deprecated = 0x200,
		HideIcons = 0x400,
		HideVignettes = 0x800,
		ForceAllOverlayExplored = 0x1000,
		FlightMapShowZoomOut = 0x2000,
		FlightMapAutoZoom = 0x4000,
		ForceOnNavbar = 0x8000,
		AlwaysAllowUserWaypoints = 0x10000,
	},
	UIMapSystem = {
		World = 0,
		Taxi = 1,
		Adventure = 2,
		Minimap = 3,
	},
	UIMapType = {
		Cosmic = 0,
		World = 1,
		Continent = 2,
		Zone = 3,
		Dungeon = 4,
		Micro = 5,
		Orphan = 6,
	},
	UIModelSceneContext = {
		None = -1,
		PerksProgram = 0,
	},
	UIModelSceneFlags = {
		SheatheWeapon = 1,
		HideWeapon = 2,
		Autodress = 4,
	},
	UISystemType = {
		InGameNavigation = 0,
	},
	UIWidgetBlendModeType = {
		Opaque = 0,
		Additive = 1,
	},
	UIWidgetFlag = {
		UniversalWidget = 1,
	},
	UIWidgetFontType = {
		Normal = 0,
		Shadow = 1,
		Outline = 2,
	},
	UIWidgetLayoutDirection = {
		Default = 0,
		Vertical = 1,
		Horizontal = 2,
		Overlap = 3,
		HorizontalForceNewRow = 4,
	},
	UIWidgetModelSceneLayer = {
		None = 0,
		Front = 1,
		Back = 2,
	},
	UIWidgetMotionType = {
		Instant = 0,
		Smooth = 1,
	},
	UIWidgetScale = {
		OneHundred = 0,
		Ninty = 1,
		Eighty = 2,
		Seventy = 3,
		Sixty = 4,
		Fifty = 5,
	},
	UIWidgetSetLayoutDirection = {
		Vertical = 0,
		Horizontal = 1,
	},
	UIWidgetTextSizeType = {
		Small12Pt = 0,
		Medium16Pt = 1,
		Large24Pt = 2,
		Huge27Pt = 3,
		Standard14Pt = 4,
		Small10Pt = 5,
		Small11Pt = 6,
		Medium18Pt = 7,
		Large20Pt = 8,
	},
	UIWidgetTextureAndTextSizeType = {
		Small = 0,
		Medium = 1,
		Large = 2,
		Huge = 3,
		Standard = 4,
	},
	UIWidgetTooltipLocation = {
		Default = 0,
		BottomLeft = 1,
		Left = 2,
		TopLeft = 3,
		Top = 4,
		TopRight = 5,
		Right = 6,
		BottomRight = 7,
		Bottom = 8,
	},
	UIWidgetVisualizationType = {
		IconAndText = 0,
		CaptureBar = 1,
		StatusBar = 2,
		DoubleStatusBar = 3,
		IconTextAndBackground = 4,
		DoubleIconAndText = 5,
		StackedResourceTracker = 6,
		IconTextAndCurrencies = 7,
		TextWithState = 8,
		HorizontalCurrencies = 9,
		BulletTextList = 10,
		ScenarioHeaderCurrenciesAndBackground = 11,
		TextureAndText = 12,
		SpellDisplay = 13,
		DoubleStateIconRow = 14,
		TextureAndTextRow = 15,
		ZoneControl = 16,
		CaptureZone = 17,
		TextureWithAnimation = 18,
		DiscreteProgressSteps = 19,
		ScenarioHeaderTimer = 20,
		TextColumnRow = 21,
		Spacer = 22,
		UnitPowerBar = 23,
		FillUpFrames = 24,
		TextWithSubtext = 25,
	},
	UnitSex = {
		Male = 0,
		Female = 1,
		None = 2,
		Both = 3,
		Neutral = 4,
	},
	ValidateNameResult = {
		Success = 0,
		Failure = 1,
		NoName = 2,
		TooShort = 3,
		TooLong = 4,
		InvalidCharacter = 5,
		MixedLanguages = 6,
		Profane = 7,
		Reserved = 8,
		InvalidApostrophe = 9,
		MultipleApostrophes = 10,
		ThreeConsecutive = 11,
		InvalidSpace = 12,
		ConsecutiveSpaces = 13,
		RussianConsecutiveSilentCharacters = 14,
		RussianSilentCharacterAtBeginningOrEnd = 15,
		DeclensionDoesntMatchBaseName = 16,
		SpacesDisallowed = 17,
	},
	VasPurchaseProgress = {
		Invalid = 0,
		PrePurchase = 1,
		PaymentPending = 2,
		ApplyingLicense = 3,
		WaitingOnQueue = 4,
		Ready = 5,
		ProcessingFactionChange = 6,
		Complete = 7,
	},
	ViewRaidSize = {
		Ten = 0,
		TwentyFive = 1,
		Forty = 2,
	},
	VignetteType = {
		Normal = 0,
		PvPBounty = 1,
		Torghast = 2,
		Treasure = 3,
	},
	VoiceChannelErrorReason = {
		Unknown = 0,
		IsBattleNetChannel = 1,
	},
	VoiceChatStatusCode = {
		Success = 0,
		OperationPending = 1,
		TooManyRequests = 2,
		LoginProhibited = 3,
		ClientNotInitialized = 4,
		ClientNotLoggedIn = 5,
		ClientAlreadyLoggedIn = 6,
		ChannelNameTooShort = 7,
		ChannelNameTooLong = 8,
		ChannelAlreadyExists = 9,
		AlreadyInChannel = 10,
		TargetNotFound = 11,
		Failure = 12,
		ServiceLost = 13,
		UnableToLaunchProxy = 14,
		ProxyConnectionTimeOut = 15,
		ProxyConnectionUnableToConnect = 16,
		ProxyConnectionUnexpectedDisconnect = 17,
		Disabled = 18,
		UnsupportedChatChannelType = 19,
		InvalidCommunityStream = 20,
		PlayerSilenced = 21,
		PlayerVoiceChatParentalDisabled = 22,
		InvalidInputDevice = 23,
		InvalidOutputDevice = 24,
	},
	VoiceTtsDestination = {
		RemoteTransmission = 0,
		LocalPlayback = 1,
		RemoteTransmissionWithLocalPlayback = 2,
		QueuedRemoteTransmission = 3,
		QueuedLocalPlayback = 4,
		QueuedRemoteTransmissionWithLocalPlayback = 5,
		ScreenReader = 6,
	},
	VoiceTtsStatusCode = {
		Success = 0,
		InvalidEngineType = 1,
		EngineAllocationFailed = 2,
		NotSupported = 3,
		MaxCharactersExceeded = 4,
		UtteranceBelowMinimumDuration = 5,
		InputTextEnqueued = 6,
		SdkNotInitialized = 7,
		DestinationQueueFull = 8,
		EnqueueNotNecessary = 9,
		UtteranceNotFound = 10,
		ManagerNotFound = 11,
		InvalidArgument = 12,
		InternalError = 13,
	},
	WeeklyRewardChestThresholdType = {
		None = 0,
		MythicPlus = 1,
		RankedPvP = 2,
		Raid = 3,
		AlsoReceive = 4,
		Concession = 5,
	},
	WidgetAnimationType = {
		None = 0,
		Fade = 1,
	},
	WidgetCurrencyClass = {
		Currency = 0,
		Item = 1,
	},
	WidgetEnabledState = {
		Disabled = 0,
		Enabled = 1,
		Red = 2,
		White = 3,
		Green = 4,
		Gold = 5,
		Black = 6,
	},
	WidgetShownState = {
		Hidden = 0,
		Shown = 1,
	},
	WidgetTextHorizontalAlignmentType = {
		Left = 0,
		Center = 1,
		Right = 2,
	},
	WidgetUnitPowerBarFlashMomentType = {
		FlashWhenMax = 0,
		FlashWhenMin = 1,
		NeverFlash = 2,
	},
	WoWEntitlementType = {
		Item = 0,
		Mount = 1,
		Battlepet = 2,
		Toy = 3,
		Appearance = 4,
		AppearanceSet = 5,
		GameTime = 6,
		Title = 7,
		Illusion = 8,
		Invalid = 9,
	},
	WorldCursorAnchorType = {
		None = 0,
		Default = 1,
		Cursor = 2,
		Nameplate = 3,
	},
	WorldQuestQuality = {
		Common = 0,
		Rare = 1,
		Epic = 2,
	},
	ZoneControlActiveState = {
		Inactive = 0,
		Active = 1,
	},
	ZoneControlDangerFlashType = {
		ShowOnGoodStates = 0,
		ShowOnBadStates = 1,
		ShowOnBoth = 2,
		ShowOnNeither = 3,
	},
	ZoneControlFillType = {
		SingleFillClockwise = 0,
		SingleFillCounterClockwise = 1,
		DoubleFillClockwise = 2,
		DoubleFillCounterClockwise = 3,
	},
	ZoneControlLeadingEdgeType = {
		NoLeadingEdge = 0,
		UseLeadingEdge = 1,
	},
	ZoneControlMode = {
		BothStatesAreGood = 0,
		State1IsGood = 1,
		State2IsGood = 2,
		NeitherStateIsGood = 3,
	},
	ZoneControlState = {
		State1 = 0,
		State2 = 1,
	},
}

Constants = {
	AuctionConstants = {
		DEFAULT_AUCTION_PRICE_MULTIPLIER = 1.5,
	},
	CalendarGetEventTypeConstants = {
		DEFAULT_CALENDAR_GET_EVENT_TYPE = 0,
	},
	Callings = {
		MaxCallings = 3,
	},
	CharCustomizationConstants = {
		NUM_CUSTOM_DISPLAY = 4,
		CHAR_CUSTOMIZE_CUSTOM_DISPLAY_OPTION_FIRST = 5,
		CHAR_CUSTOMIZE_CUSTOM_DISPLAY_OPTION_LAST = 8,
	},
	CraftingOrderConsts = {
		MAX_CRAFTING_ORDER_FAVORITE_RECIPES = 100,
	},
	CurrencyConsts = {
		CATALYST_CHARGE_CAP = 6,
		HONOR_PER_CURRENCY = 10,
		PLAYER_CURRENCY_CLIENT_FLAGS = 12,
		CONQUEST_ARENA_AND_BG_META_CURRENCY_ID = 483,
		CONQUEST_RATED_BG_META_CURRENCY_ID = 484,
		CONQUEST_ASHRAN_META_CURRENCY_ID = 692,
		ARTIFACT_KNOWLEDGE_CURRENCY_ID = 1171,
		WAR_RESOURCES_CURRENCY_ID = 1560,
		ACCOUNT_WIDE_HONOR_CURRENCY_ID = 1585,
		ACCOUNT_WIDE_HONOR_LEVEL_CURRENCY_ID = 1586,
		CONQUEST_CURRENCY_ID = 1602,
		HONOR_CURRENCY_ID = 1792,
		ECHOES_OF_NYALOTHA_CURRENCY_ID = 1803,
		CURRENCY_ID_WILLING_SOUL = 1810,
		CURRENCY_ID_RESERVOIR_ANIMA = 1813,
		CURRENCY_ID_RENOWN = 1822,
		CURRENCY_ID_RENOWN_KYRIAN = 1829,
		CURRENCY_ID_RENOWN_VENTHYR = 1830,
		CURRENCY_ID_RENOWN_NIGHT_FAE = 1831,
		CURRENCY_ID_RENOWN_NECROLORD = 1832,
		CLASSIC_ARENA_POINTS_CURRENCY_ID = 1900,
		CLASSIC_HONOR_CURRENCY_ID = 1901,
		CURRENCY_ID_PERKS_PROGRAM_DISPLAY_INFO = 2032,
		CURRENCY_ID_ACCOUNT_WIDE_CATALYST_CHARGES = 2166,
		CURRENCY_ID_PERSONAL_CATALYST_CHARGES = 2167,
		QUESTIONMARK_INV_ICON = 134400,
		MAX_CURRENCY_QUANTITY = 100000000,
	},
	EditModeConsts = {
		EditModeMaxLayoutsPerType = 5,
		EditModeMinGridSpacing = 20,
		EditModeDefaultGridSpacing = 100,
		EditModeMaxGridSpacing = 300,
	},
	ITEM_WEAPON_SUBCLASSConstants = {
		ITEM_WEAPON_SUBCLASS_NONE = -1,
	},
	InventoryConstants = {
		NumReagentBagSlots = 1,
		NumBagSlots = 4,
		NumBankBagSlots = 7,
		NumGenericBankSlots = 28,
	},
	ItemConsts = {
		NUM_ITEM_ENCHANTMENT_SOCKETS = 3,
	},
	LevelConstsExposed = {
		MIN_ACHIEVEMENT_LEVEL = 10,
		MIN_RES_SICKNESS_LEVEL = 10,
	},
	LootConsts = {
		MasterLootQualityThreshold = 5,
	},
	ProfessionConsts = {
		NUM_PRIMARY_PROFESSIONS = 2,
		CLASSIC_PROFESSION_PARENT_TIER_INDEX = 4,
		MAX_CRAFTING_REAGENT_SLOTS = 12,
		CRAFTING_ORDER_ITEM_RETENTION = 30,
		RUNEFORGING_ROOT_CATEGORY_ID = 210,
		RUNEFORGING_SKILL_LINE_ID = 960,
		CRAFTING_ORDER_CLAIM_DURATION = 1800,
		PUBLIC_CRAFTING_ORDER_STALE_THRESHOLD = 14400,
	},
	PvpInfoConsts = {
		MaxPlayersPerInstance = 80,
	},
	QuestWatchConsts = {
		MAX_WORLD_QUEST_WATCHES_AUTOMATIC = 1,
		MAX_WORLD_QUEST_WATCHES_MANUAL = 5,
		MAX_QUEST_WATCHES = 25,
	},
	TraitConsts = {
		STARTER_BUILD_TRAIT_CONFIG_ID = -2,
		INSPECT_TRAIT_CONFIG_ID = -1,
		MAX_COMBAT_TRAIT_CONFIGS = 10,
		COMMIT_COMBAT_TRAIT_CONFIG_CHANGES_SPELL_ID = 384255,
	},
	Transmog = {
		MainHandTransmogIsIndividualWeapon = -1,
		MainHandTransmogIsPairedWeapon = 0,
		NoTransmogID = 0,
	},
}

NUM_LE_ACTIONBAR_VISUAL_STATES = 2
LE_ACTIONBAR_STATE_MAIN = 1
LE_ACTIONBAR_STATE_OVERRIDE = 2

NUM_LE_AURORA_STATES = 8
LE_AURORA_STATE_NONE = 1
LE_AURORA_STATE_CONNECTING = 2
LE_AURORA_STATE_CONNECTED = 3
LE_AURORA_STATE_DISCONNECTING = 4
LE_AURORA_STATE_LEGAL_AGREEMENT = 5
LE_AURORA_STATE_SELECT_ACCOUNT = 6
LE_AURORA_STATE_ENTER_CAPTCHA = 7
LE_AURORA_STATE_ENTER_EXTRA_AUTH = 8

NUM_LE_AUTHS = 2
LE_AUTH_NONE = 1
LE_AUTH_AUTHENTICATOR = 2

NUM_LE_AUTOCOMPLETE_PRIORITYS = 7
LE_AUTOCOMPLETE_PRIORITY_OTHER = 1
LE_AUTOCOMPLETE_PRIORITY_INTERACTED = 2
LE_AUTOCOMPLETE_PRIORITY_IN_GROUP = 3
LE_AUTOCOMPLETE_PRIORITY_GUILD = 4
LE_AUTOCOMPLETE_PRIORITY_FRIEND = 5
LE_AUTOCOMPLETE_PRIORITY_ACCOUNT_CHARACTER = 6
LE_AUTOCOMPLETE_PRIORITY_ACCOUNT_CHARACTER_SAME_REALM = 7

NUM_LE_CHARACTER_UNDELETE_RESULTS = 7
LE_CHARACTER_UNDELETE_RESULT_OK = 1
LE_CHARACTER_UNDELETE_RESULT_ERROR_COOLDOWN = 2
LE_CHARACTER_UNDELETE_RESULT_ERROR_CHAR_CREATE = 3
LE_CHARACTER_UNDELETE_RESULT_ERROR_DISABLED = 4
LE_CHARACTER_UNDELETE_RESULT_ERROR_NAME_TAKEN_BY_THIS_ACCOUNT = 5
LE_CHARACTER_UNDELETE_RESULT_ERROR_DRACTHYR_LEVEL_REQUIREMENT = 6
LE_CHARACTER_UNDELETE_RESULT_ERROR_UNKNOWN = 7

NUM_LE_CHARACTER_UPGRADE_RESULTS = 13
LE_CHARACTER_UPGRADE_RESULT_OK = 1
LE_CHARACTER_UPGRADE_RESULT_DB_ERROR = 2
LE_CHARACTER_UPGRADE_RESULT_TRIAL_THROTTLE_HOUR = 3
LE_CHARACTER_UPGRADE_RESULT_TRIAL_THROTTLE_DAY = 4
LE_CHARACTER_UPGRADE_RESULT_TRIAL_THROTTLE_WEEK = 5
LE_CHARACTER_UPGRADE_RESULT_TRIAL_THROTTLE_ACCOUNT = 6
LE_CHARACTER_UPGRADE_RESULT_BOX_LEVEL = 7
LE_CHARACTER_UPGRADE_RESULT_TRIAL_BOOST_DISABLED = 8
LE_CHARACTER_UPGRADE_RESULT_TRIAL_ACCOUNT = 9
LE_CHARACTER_UPGRADE_RESULT_UPGRADE_PENDING = 10
LE_CHARACTER_UPGRADE_RESULT_INVALID_CHARACTER = 11
LE_CHARACTER_UPGRADE_RESULT_NOT_FRESH_CHARACTER = 12

NUM_LE_EXPANSION_LEVELS = 9
LE_EXPANSION_CLASSIC = 0
LE_EXPANSION_BURNING_CRUSADE = 1
LE_EXPANSION_WRATH_OF_THE_LICH_KING = 2
LE_EXPANSION_CATACLYSM = 3
LE_EXPANSION_MISTS_OF_PANDARIA = 4
LE_EXPANSION_WARLORDS_OF_DRAENOR = 5
LE_EXPANSION_LEGION = 6
LE_EXPANSION_BATTLE_FOR_AZEROTH = 7
LE_EXPANSION_LEVEL_PREVIOUS = 8
LE_EXPANSION_SHADOWLANDS = 8
LE_EXPANSION_DRAGONFLIGHT = 9
LE_EXPANSION_LEVEL_CURRENT = 9
LE_EXPANSION_11_0 = 10

NUM_LE_FRAME_TUTORIALS = 150
LE_FRAME_TUTORIAL_TALENT = 1
LE_FRAME_TUTORIAL_SPEC = 2
LE_FRAME_TUTORIAL_GLYPH = 3
LE_FRAME_TUTORIAL_SPELLBOOK = 4
LE_FRAME_TUTORIAL_PROFESSIONS = 5
LE_FRAME_TUTORIAL_CORE_ABILITITES = 6
LE_FRAME_TUTORIAL_PET_JOURNAL = 7
LE_FRAME_TUTORIAL_WHAT_HAS_CHANGED = 8
LE_FRAME_TUTORIAL_GARRISON_BUILDING = 9
LE_FRAME_TUTORIAL_GARRISON_MISSION_LIST = 10
LE_FRAME_TUTORIAL_GARRISON_MISSION_PAGE = 11
LE_FRAME_TUTORIAL_GARRISON_LANDING = 12
LE_FRAME_TUTORIAL_GARRISON_ZONE_ABILITY = 13
LE_FRAME_TUTORIAL_WORLD_MAP_FRAME = 14
LE_FRAME_TUTORIAL_CLEAN_UP_BAGS = 15
LE_FRAME_TUTORIAL_BAG_SETTINGS = 16
LE_FRAME_TUTORIAL_REAGENT_BANK_UNLOCK = 17
LE_FRAME_TUTORIAL_TOYBOX_FAVORITE = 18
LE_FRAME_TUTORIAL_TOYBOX_MOUSEWHEEL_PAGING = 19
LE_FRAME_TUTORIAL_LFG_LIST = 20
LE_FRAME_TUTORIAL_TOYBOX = 21
LE_FRAME_TUTORIAL_HEIRLOOM_JOURNAL = 22
LE_FRAME_TUTORIAL_HEIRLOOM_JOURNAL_TAB = 23
LE_FRAME_TUTORIAL_HEIRLOOM_JOURNAL_LEVEL = 24
LE_FRAME_TUTORIAL_GAME_TIME_AUCTION_HOUSE = 25
LE_FRAME_TUTORIAL_BOOSTED_SPELL_BOOK = 26
LE_FRAME_TUTORIAL_ARTIFACT_KNOWLEDGE_LEVEL_LIMIT = 27
LE_FRAME_TUTORIAL_WRAPPED_COLLECTION_ITEMS = 28
LE_FRAME_TUTORIAL_VIEWABLE_ARTIFACT = 29
LE_FRAME_TUTORIAL_ARTIFACT_APPEARANCE_TAB = 30
LE_FRAME_TUTORIAL_ARTIFACT_RELIC_MATCH = 31
LE_FRAME_TUTORIAL_BOUNTY_INTRO = 32
LE_FRAME_TUTORIAL_BOUNTY_FINISHED = 33
LE_FRAME_TUTORIAL_IGNORE_QUEST = 34
LE_FRAME_TUTORIAL_TRANSMOG_JOURNAL_TAB = 35
LE_FRAME_TUTORIAL_TRANSMOG_MODEL_CLICK = 36
LE_FRAME_TUTORIAL_TRANSMOG_SPECS_BUTTON = 37
LE_FRAME_TUTORIAL_TRANSMOG_OUTFIT_DROPDOWN = 38
LE_FRAME_TUTORIAL_HONOR_TALENT_FIRST_TALENT = 39
LE_FRAME_TUTORIAL_HONOR_TALENT_HONOR_LEVELS = 40
LE_FRAME_TUTORIAL_ARTIFACT_KNOWLEDGE = 41
LE_FRAME_TUTORIAL_INVENTORY_FIXUP_EXPANSION_LEGION = 42
LE_FRAME_TUTORIAL_INVENTORY_FIXUP_CHECK_EXPANSION_LEGION = 43
LE_FRAME_TUTORIAL_BONUS_ROLL_ENCOUNTER_JOURNAL_LINK = 44
LE_FRAME_TUTORIAL_FRIENDS_LIST_QUICK_JOIN = 45
LE_FRAME_TUTORIAL_REPUTATION_EXALTED_PLUS = 46
LE_FRAME_TUTORIAL_TRANSMOG_SETS_TAB = 47
LE_FRAME_TUTORIAL_TRANSMOG_SETS_VENDOR_TAB = 48
LE_FRAME_TUTORIAL_BRAWL = 49
LE_FRAME_TUTORIAL_RELIC_FORGE_LEARN_TRAIT = 50
LE_FRAME_TUTORIAL_RELIC_FORGE_SOCKETED_RELIC = 51
LE_FRAME_TUTORIAL_RELIC_FORGE_PREVIEW_RELIC = 52
LE_FRAME_TUTORIAL_BAG_SLOTS_AUTHENTICATOR = 53
LE_FRAME_TUTORIAL_TRIAL_BANKED_XP = 54
LE_FRAME_TUTORIAL_TRADESKILL_UNLEARNED_TAB = 55
LE_FRAME_TUTORIAL_TRADESKILL_RANK_STAR = 56
LE_FRAME_TUTORIAL_AZERITE_RESPEC = 57
LE_FRAME_TUTORIAL_PVP_TALENTS_FIRST_UNLOCK = 58
LE_FRAME_TUTORIAL_PVP_WARMODE_UNLOCK = 59
LE_FRAME_TUTORIAL_WARFRONT_RESOURCES = 60
LE_FRAME_TUTORIAL_WARFRONT_CONSTRUCTION = 61
LE_FRAME_TUTORIAL_AZERITE_ITEM_IN_BAG = 62
LE_FRAME_TUTORIAL_AZERITE_ITEM_IN_SLOT = 63
LE_FRAME_TUTORIAL_AZERITE_FIRST_POWER_LOCKED_IN = 64
LE_FRAME_TUTORIAL_CHAT_CHANNELS = 65
LE_FRAME_TUTORIAL_ISLANDS_QUEUE_BUTTON = 66
LE_FRAME_TUTORIAL_ISLANDS_QUEUE_INFO_FRAME = 67
LE_FRAME_TUTORIAL_MOUNT_EQUIPMENT_SLOT_FRAME = 68
LE_FRAME_TUTORIAL_QUEST_SESSION = 69
LE_FRAME_TUTORIAL_CLUB_FINDER_NEW_GUILD_LEADER = 70
LE_FRAME_TUTORIAL_CLUB_FINDER_NEW_COMMUNITY_LEADER = 71
LE_FRAME_TUTORIAL_CLUB_FINDER_NEW_APPLICANTS_GUILD_LEADER = 72
LE_FRAME_TUTORIAL_CLUB_FINDER_LINKING = 73
LE_FRAME_TUTORIAL_PVP_SPECIAL_EVENT = 74
LE_FRAME_TUTORIAL_WORLD_MAP_THREAT_ICON = 75
LE_FRAME_TUTORIAL_CORRUPTION_CLEANSER = 76
LE_FRAME_TUTORIAL_RUNECARVER_SCRAPPING = 77
LE_FRAME_TUTORIAL_CLUB_FINDER_NEW_LANGUAGE_FILTER = 78
LE_FRAME_TUTORIAL_OPTIONAL_REAGENT_CRAFTING = 79
LE_FRAME_TUTORIAL_CAMPAIGN_LORE_TEXT = 80
LE_FRAME_TUTORIAL_NEWCOMER_GRADUATION = 81
LE_FRAME_TUTORIAL_NEWCOMER_GRADUATION_REMINDER = 82
LE_FRAME_TUTORIAL_RUNEFORGE_LEGENDARY_CRAFT = 83
LE_FRAME_TUTORIAL_ANIMA_DIVERSION_SPEND_ANIMA = 84
LE_FRAME_TUTORIAL_ANIMA_DIVERSION_FILL_BAR = 85
LE_FRAME_TUTORIAL_ANIMA_DIVERSION_ACTIVATE_LOCATION = 86
LE_FRAME_TUTORIAL_ANIMA_DIVERSION_REINFORCE_LOCATION = 87
LE_FRAME_TUTORIAL_9_0_GRRISON_LANDING_PAGE_BUTTON_CALLINGS = 88
LE_FRAME_TUTORIAL_9_0_GRRISON_LANDING_PAGE_CALLINGS = 89
LE_FRAME_TUTORIAL_9_0_JAILERS_TOWER_BUFFS = 90
LE_FRAME_TUTORIAL_EMBER_COURT_MAP = 91
LE_FRAME_TUTORIAL_EYE_OF_JAILER = 92
LE_FRAME_TUTORIAL_SOULBIND_PATH_SELECT = 93
LE_FRAME_TUTORIAL_SOULBIND_CONDUIT_INSTALL = 94
LE_FRAME_TUTORIAL_SOULBIND_CONDUIT_LEARN = 95
LE_FRAME_TUTORIAL_FIRST_RUNEFORGE_LEGENDARY_POWER = 96
LE_FRAME_TUTORIAL_COVENANT_RENOWN_REWARDS = 97
LE_FRAME_TUTORIAL_COVENANT_RENOWN_PROGRESS = 98
LE_FRAME_TUTORIAL_COVENANT_RESERVOIR_DEPOSIT = 99
LE_FRAME_TUTORIAL_COVENANT_RESERVOIR_FEATURES = 100
LE_FRAME_TUTORIAL_TEXT_TO_SPEECH = 101
LE_FRAME_TUTORIAL_SPEECH_TO_TEXT = 102
LE_FRAME_TUTORIAL_SOULBIND_ENHANCED_CONDUIT = 103
LE_FRAME_TUTORIAL_TORGHAST_REROLL = 104
LE_FRAME_TUTORIAL_TORGHAST_EARN_TOWER_KNOWLEDGE = 105
LE_FRAME_TUTORIAL_TORGHAST_SPEND_TOWER_KNOWLEDGE = 106
LE_FRAME_TUTORIAL_TORGHAST_DOMINANCE_BAR = 107
LE_FRAME_TUTORIAL_TORGHAST_DOMINANCE_BAR_CUTOFF = 108
LE_FRAME_TUTORIAL_UPGRADEABLE_ITEM_IN_SLOT = 109
LE_FRAME_TUTORIAL_LINK_TRANSMOG_OUTFIT = 110
LE_FRAME_TUTORIAL_GREAT_VAULT_CLASS_SETS = 111
LE_FRAME_TUTORIAL_CROSS_FACTION_INVITE = 112
LE_FRAME_TUTORIAL_CROSS_FACTION_GROUP_FINDER = 113
LE_FRAME_TUTORIAL_CROSS_FACTION_COMMUNITY = 114
LE_FRAME_TUTORIAL_MOUNT_COLLECTION_DRAGONRIDING = 115
LE_FRAME_TUTORIAL_MAJOR_FACTION_RENOWN_PROGRESS = 116
LE_FRAME_TUTORIAL_HUD_REVAMP_TRACKING_CHANGES = 117
LE_FRAME_TUTORIAL_HUD_REVAMP_UNIT_FRAME_CHANGES = 118
LE_FRAME_TUTORIAL_HUD_REVAMP_BAG_CHANGES = 119
LE_FRAME_TUTORIAL_HUD_REVAMP_LFG_QUEUE_CHANGES = 120
LE_FRAME_TUTORIAL_SPEC_CHANGES = 121
LE_FRAME_TUTORIAL_TALENT_CHANGES = 122
LE_FRAME_TUTORIAL_TALENT_STARTER_HELP = 123
LE_FRAME_TUTORIAL_EQUIP_REAGENT_BAG = 124
LE_FRAME_TUTORIAL_DRACTHYR_ESSENCE = 125
LE_FRAME_TUTORIAL_DRACTHYR_EMPOWERED = 126
LE_FRAME_TUTORIAL_DRACTHYR_LOW_HEALTH = 127
LE_FRAME_TUTORIAL_DRAGON_RIDING_GLYPHS = 128
LE_FRAME_TUTORIAL_SETTINGS_SEARCH = 129
LE_FRAME_TUTORIAL_PROFESSIONS_SPEC_CHOICE = 130
LE_FRAME_TUTORIAL_WORLD_MAP_ACTIVITY_TRACKER_LIST = 131
LE_FRAME_TUTORIAL_PROFESSIONS_CO_QUALITY_REAGENTS = 132
LE_FRAME_TUTORIAL_PROFESSIONS_CO_OPTIONAL_REAGENTS = 133
LE_FRAME_TUTORIAL_PROFESSIONS_CO_ORDER_PLACED = 134
LE_FRAME_TUTORIAL_PROFESSIONS_RECRAFT = 135
LE_FRAME_TUTORIAL_FIRST_PROFESSION = 136
LE_FRAME_TUTORIAL_PROFESSION_QUALITY_REAGENTS = 137
LE_FRAME_TUTORIAL_PROFESSION_OPTIONAL_REAGENTS_NEW = 138
LE_FRAME_TUTORIAL_PROFESSION_QUALITY_BAR = 139
LE_FRAME_TUTORIAL_PROFESSION_FINISHING_REAGENTS = 140
LE_FRAME_TUTORIAL_EDIT_MODE_MANAGER = 141
LE_FRAME_TUTORIAL_DRAGON_RIDING_SKILLS = 142
LE_FRAME_TUTORIAL_DRAGON_RIDING_ACTIONBAR = 143
LE_FRAME_TUTORIAL_PERKS_PROGRAM_FREEZE_ITEM = 144
LE_FRAME_TUTORIAL_PERKS_PROGRAM_HIDE_ARMOR = 145
LE_FRAME_TUTORIAL_PERKS_PROGRAM_NEW_COLLECTION_ITEM = 146
LE_FRAME_TUTORIAL_PERKS_PROGRAM_ACTIVITIES_OPEN = 147
LE_FRAME_TUTORIAL_PERKS_PROGRAM_ACTIVITIES_INTRO = 148
LE_FRAME_TUTORIAL_PERKS_PROGRAM_ACTIVITIES_MAX_INFLUENCE = 149
LE_FRAME_TUTORIAL_PERKS_PROGRAM_ACTIVITIES_TRACKING = 150

NUM_LE_FRAME_TUTORIAL_ACCCOUNTS = 3
LE_FRAME_TUTORIAL_ACCCOUNT_RAF_INTRO = 1
LE_FRAME_TUTORIAL_ACCCOUNT_CLUB_FINDER_NEW_FEATURE = 2
LE_FRAME_TUTORIAL_ACCOUNT_CLUB_FINDER_NEW_COMMUNITY_JOINED = 3

NUM_LE_INVITE_REQUEST_TYPES = 3
LE_INVITE_CONFIRMATION_REQUEST = 1
LE_INVITE_CONFIRMATION_SUGGEST = 2
LE_INVITE_CONFIRMATION_QUEUE_WARNING = 3

NUM_LE_ITEM_BIND_TYPES = 5
LE_ITEM_BIND_NONE = 0
LE_ITEM_BIND_ON_ACQUIRE = 1
LE_ITEM_BIND_ON_EQUIP = 2
LE_ITEM_BIND_ON_USE = 3
LE_ITEM_BIND_QUEST = 4

NUM_LE_LFG_CATEGORYS = 7
LE_LFG_CATEGORY_LFD = 1
LE_LFG_CATEGORY_LFR = 2
LE_LFG_CATEGORY_RF = 3
LE_LFG_CATEGORY_SCENARIO = 4
LE_LFG_CATEGORY_FLEXRAID = 5
LE_LFG_CATEGORY_WORLDPVP = 6
LE_LFG_CATEGORY_BATTLEFIELD = 7

NUM_LE_LFG_LIST_DISPLAY_TYPES = 5
LE_LFG_LIST_DISPLAY_TYPE_ROLE_COUNT = 1
LE_LFG_LIST_DISPLAY_TYPE_ROLE_ENUMERATE = 2
LE_LFG_LIST_DISPLAY_TYPE_CLASS_ENUMERATE = 3
LE_LFG_LIST_DISPLAY_TYPE_HIDE_ALL = 4
LE_LFG_LIST_DISPLAY_TYPE_PLAYER_COUNT = 5

LE_LOOT_FILTER_ALL = 1
LE_LOOT_FILTER_CLASS = 2
LE_LOOT_FILTER_SPEC1 = 3
LE_LOOT_FILTER_SPEC2 = 4
LE_LOOT_FILTER_SPEC3 = 5
LE_LOOT_FILTER_SPEC4 = 6
LE_LOOT_FILTER_BOE = 7

NUM_LE_MODEL_BLEND_OPERATIONS = 2
LE_MODEL_BLEND_OPERATION_NONE = 1
LE_MODEL_BLEND_OPERATION_ANIM = 2

NUM_LE_MODEL_LIGHT_TYPES = 2
LE_MODEL_LIGHT_TYPE_DIRECTIONAL = 1
LE_MODEL_LIGHT_TYPE_POINT = 2

NUM_LE_MOUNT_JOURNAL_FILTERS = 3
LE_MOUNT_JOURNAL_FILTER_COLLECTED = 1
LE_MOUNT_JOURNAL_FILTER_NOT_COLLECTED = 2
LE_MOUNT_JOURNAL_FILTER_UNUSABLE = 3

LE_NUM_BONUS_ACTION_PAGES = 5
LE_NUM_NORMAL_ACTION_PAGES = 6
LE_NUM_ACTIONS_PER_PAGE = 12
LE_NUM_CHARACTER_UPGRADE_RESULT = 13

NUM_LE_CINEMATIC_PAN_TYPES = 6
LE_PAN_STEADY = 1
LE_PAN_NONE = 2
LE_PAN_NONE_RANGED = 3
LE_PAN_FAST_SLOW = 4
LE_PAN_SLOW_FAST = 5
LE_PAN_AND_JUMP = 6

NUM_LE_PARTY_CATEGORYS = 2
LE_PARTY_CATEGORY_HOME = 1
LE_PARTY_CATEGORY_INSTANCE = 2

NUM_LE_PET_JOURNAL_FILTERS = 2
LE_PET_JOURNAL_FILTER_COLLECTED = 1
LE_PET_JOURNAL_FILTER_NOT_COLLECTED = 2

NUM_LE_QUEST_FACTIONS = 2
LE_QUEST_FACTION_ALLIANCE = 1
LE_QUEST_FACTION_HORDE = 2

NUM_LE_REALM_RELATIONS = 3
LE_REALM_RELATION_SAME = 1
LE_REALM_RELATION_COALESCED = 2
LE_REALM_RELATION_VIRTUAL = 3

NUM_LE_SCENARIO_TYPES = 7
LE_SCENARIO_TYPE_DEFAULT = 0
LE_SCENARIO_TYPE_CHALLENGE_MODE = 1
LE_SCENARIO_TYPE_PROVING_GROUNDS = 2
LE_SCENARIO_TYPE_USE_DUNGEON_DISPLAY = 3
LE_SCENARIO_TYPE_LEGION_INVASION = 4
LE_SCENARIO_TYPE_BOOST_TUTORIAL = 5
LE_SCENARIO_TYPE_WARFRONT = 6

NUM_LE_SCRIPT_BINDING_TYPES = 2
LE_SCRIPT_BINDING_TYPE_INTRINSIC_PRECALL = 0
LE_SCRIPT_BINDING_TYPE_EXTRINSIC = 1
LE_SCRIPT_BINDING_TYPE_INTRINSIC_POSTCALL = 2

NUM_LE_PET_SORT_PARAMETERS = 4
LE_SORT_BY_NAME = 1
LE_SORT_BY_LEVEL = 2
LE_SORT_BY_RARITY = 3
LE_SORT_BY_PETTYPE = 4

NUM_LE_SPELL_CONFIRMATION_PROMPT_TYPES = 3
LE_SPELL_CONFIRMATION_PROMPT_TYPE_STATIC_TEXT = 0
LE_SPELL_CONFIRMATION_PROMPT_TYPE_BONUS_ROLL = 1
LE_SPELL_CONFIRMATION_PROMPT_TYPE_SIMPLE_WARNING = 2

NUM_LE_SUMMON_REASONS = 2
LE_SUMMON_REASON_SPELL = 0
LE_SUMMON_REASON_SCENARIO = 1

NUM_LE_GM_WEB_TICKET_STATUSS = 4
LE_TICKET_STATUS_OPEN = 1
LE_TICKET_STATUS_SURVEY = 2
LE_TICKET_STATUS_NMI = 3
LE_TICKET_STATUS_RESPONSE = 4

NUM_LE_TOKEN_CHOICES = 2
LE_TOKEN_CHOICE_SUBSCRIPTION = 1
LE_TOKEN_CHOICE_BALANCE = 2

NUM_LE_TOKEN_RESULTS = 10
LE_TOKEN_RESULT_SUCCESS = 1
LE_TOKEN_RESULT_ERROR_DISABLED = 2
LE_TOKEN_RESULT_ERROR_OTHER = 3
LE_TOKEN_RESULT_ERROR_NONE_FOR_SALE = 4
LE_TOKEN_RESULT_ERROR_TOO_MANY_TOKENS = 5
LE_TOKEN_RESULT_SUCCESS_NO = 6
LE_TOKEN_RESULT_ERROR_TRANSACTION_IN_PROGRESS = 7
LE_TOKEN_RESULT_ERROR_AUCTIONABLE_TOKEN_OWNED = 8
LE_TOKEN_RESULT_ERROR_TRIAL_RESTRICTED = 9

NUM_LE_TRACKER_SORTINGS = 4
LE_TRACKER_SORTING_MANUAL = 1
LE_TRACKER_SORTING_PROXIMITY = 2
LE_TRACKER_SORTING_DIFFICULTY_LOW = 3
LE_TRACKER_SORTING_DIFFICULTY_HIGH = 4

NUM_LE_TRANSMOG_SET_FILTERS = 4
LE_TRANSMOG_SET_FILTER_COLLECTED = 1
LE_TRANSMOG_SET_FILTER_UNCOLLECTED = 2
LE_TRANSMOG_SET_FILTER_PVE = 3
LE_TRANSMOG_SET_FILTER_PVP = 4

NUM_LE_TWITTER_RESULTS = 3
LE_TWITTER_RESULT_SUCCESS = 1
LE_TWITTER_RESULT_NOT_LINKED = 2
LE_TWITTER_RESULT_FAIL = 3

NUM_LE_UNIT_STATS = 4
LE_UNIT_STAT_STRENGTH = 1
LE_UNIT_STAT_AGILITY = 2
LE_UNIT_STAT_STAMINA = 3
LE_UNIT_STAT_INTELLECT = 4

NUM_LE_VAS_PURCHASE_STATES = 8
LE_VAS_PURCHASE_STATE_INVALID = 0
LE_VAS_PURCHASE_STATE_PRE_PURCHASE = 1
LE_VAS_PURCHASE_STATE_PAYMENT_PENDING = 2
LE_VAS_PURCHASE_STATE_APPLYING_LICENSE = 3
LE_VAS_PURCHASE_STATE_READY = 5
LE_VAS_PURCHASE_STATE_PROCESSING_FACTION_CHANGE = 6
LE_VAS_PURCHASE_STATE_PROCESSING_COMPLETE = 7

NUM_LE_WORLD_ELAPSED_TIMER_TYPES = 3
LE_WORLD_ELAPSED_TIMER_TYPE_NONE = 1
LE_WORLD_ELAPSED_TIMER_TYPE_CHALLENGE_MODE = 2
LE_WORLD_ELAPSED_TIMER_TYPE_PROVING_GROUND = 3

NUM_LE_WOW_CONNECTION_STATES = 3
LE_WOW_CONNECTION_STATE_NONE = 1
LE_WOW_CONNECTION_STATE_CONNECTING = 2
LE_WOW_CONNECTION_STATE_IN_QUEUE = 3
